package com.billionsfinance.bas.entity.voucher.model;

import java.math.BigDecimal;
import java.util.Date;

public class CwVoucherModelInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ID
	 * @mbggenerated
	 */
	private BigDecimal id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.BUSINESSMODEL
	 * @mbggenerated
	 */
	private String businessmodel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.CITY
	 * @mbggenerated
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.CANCELTYPE
	 * @mbggenerated
	 */
	private String canceltype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ASSETBELONG
	 * @mbggenerated
	 */
	private String assetbelong;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.GUARANTEEPARTY
	 * @mbggenerated
	 */
	private String guaranteeparty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.RELATION
	 * @mbggenerated
	 */
	private String relation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.SPONSOR
	 * @mbggenerated
	 */
	private String sponsor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.SPONSORTYPE
	 * @mbggenerated
	 */
	private String sponsortype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.IS_INSTALMENTS_END
	 * @mbggenerated
	 */
	private String isInstalmentsEnd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.BAD_DEBT_DATE
	 * @mbggenerated
	 */
	private String badDebtDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.CALCULATED_AMOUNT_FIELD
	 * @mbggenerated
	 */
	private String calculatedAmountField;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNT_NUM
	 * @mbggenerated
	 */
	private String accountNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNT_DIR
	 * @mbggenerated
	 */
	private String accountDir;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.SUBJECT_NUM
	 * @mbggenerated
	 */
	private String subjectNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNTING_SUB
	 * @mbggenerated
	 */
	private String accountingSub;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNTING_AUX1
	 * @mbggenerated
	 */
	private String accountingAux1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNTING_AUX2
	 * @mbggenerated
	 */
	private String accountingAux2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNTING_AUX3
	 * @mbggenerated
	 */
	private String accountingAux3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNTING_ABS
	 * @mbggenerated
	 */
	private String accountingAbs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.MODEL_NO
	 * @mbggenerated
	 */
	private String modelNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.CREATE_TIME
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.UPDATE_TIME
	 * @mbggenerated
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ID
	 * @return  the value of SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ID
	 * @mbggenerated
	 */
	public BigDecimal getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ID
	 * @param id  the value for SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ID
	 * @mbggenerated
	 */
	public void setId(BigDecimal id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.BUSINESSMODEL
	 * @return  the value of SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.BUSINESSMODEL
	 * @mbggenerated
	 */
	public String getBusinessmodel() {
		return businessmodel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.BUSINESSMODEL
	 * @param businessmodel  the value for SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.BUSINESSMODEL
	 * @mbggenerated
	 */
	public void setBusinessmodel(String businessmodel) {
		this.businessmodel = businessmodel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.CITY
	 * @return  the value of SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.CITY
	 * @mbggenerated
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.CITY
	 * @param city  the value for SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.CITY
	 * @mbggenerated
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.CANCELTYPE
	 * @return  the value of SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.CANCELTYPE
	 * @mbggenerated
	 */
	public String getCanceltype() {
		return canceltype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.CANCELTYPE
	 * @param canceltype  the value for SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.CANCELTYPE
	 * @mbggenerated
	 */
	public void setCanceltype(String canceltype) {
		this.canceltype = canceltype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ASSETBELONG
	 * @return  the value of SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ASSETBELONG
	 * @mbggenerated
	 */
	public String getAssetbelong() {
		return assetbelong;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ASSETBELONG
	 * @param assetbelong  the value for SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ASSETBELONG
	 * @mbggenerated
	 */
	public void setAssetbelong(String assetbelong) {
		this.assetbelong = assetbelong;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.GUARANTEEPARTY
	 * @return  the value of SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.GUARANTEEPARTY
	 * @mbggenerated
	 */
	public String getGuaranteeparty() {
		return guaranteeparty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.GUARANTEEPARTY
	 * @param guaranteeparty  the value for SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.GUARANTEEPARTY
	 * @mbggenerated
	 */
	public void setGuaranteeparty(String guaranteeparty) {
		this.guaranteeparty = guaranteeparty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.RELATION
	 * @return  the value of SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.RELATION
	 * @mbggenerated
	 */
	public String getRelation() {
		return relation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.RELATION
	 * @param relation  the value for SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.RELATION
	 * @mbggenerated
	 */
	public void setRelation(String relation) {
		this.relation = relation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.SPONSOR
	 * @return  the value of SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.SPONSOR
	 * @mbggenerated
	 */
	public String getSponsor() {
		return sponsor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.SPONSOR
	 * @param sponsor  the value for SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.SPONSOR
	 * @mbggenerated
	 */
	public void setSponsor(String sponsor) {
		this.sponsor = sponsor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.SPONSORTYPE
	 * @return  the value of SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.SPONSORTYPE
	 * @mbggenerated
	 */
	public String getSponsortype() {
		return sponsortype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.SPONSORTYPE
	 * @param sponsortype  the value for SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.SPONSORTYPE
	 * @mbggenerated
	 */
	public void setSponsortype(String sponsortype) {
		this.sponsortype = sponsortype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.IS_INSTALMENTS_END
	 * @return  the value of SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.IS_INSTALMENTS_END
	 * @mbggenerated
	 */
	public String getIsInstalmentsEnd() {
		return isInstalmentsEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.IS_INSTALMENTS_END
	 * @param isInstalmentsEnd  the value for SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.IS_INSTALMENTS_END
	 * @mbggenerated
	 */
	public void setIsInstalmentsEnd(String isInstalmentsEnd) {
		this.isInstalmentsEnd = isInstalmentsEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.BAD_DEBT_DATE
	 * @return  the value of SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.BAD_DEBT_DATE
	 * @mbggenerated
	 */
	public String getBadDebtDate() {
		return badDebtDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.BAD_DEBT_DATE
	 * @param badDebtDate  the value for SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.BAD_DEBT_DATE
	 * @mbggenerated
	 */
	public void setBadDebtDate(String badDebtDate) {
		this.badDebtDate = badDebtDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.CALCULATED_AMOUNT_FIELD
	 * @return  the value of SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.CALCULATED_AMOUNT_FIELD
	 * @mbggenerated
	 */
	public String getCalculatedAmountField() {
		return calculatedAmountField;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.CALCULATED_AMOUNT_FIELD
	 * @param calculatedAmountField  the value for SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.CALCULATED_AMOUNT_FIELD
	 * @mbggenerated
	 */
	public void setCalculatedAmountField(String calculatedAmountField) {
		this.calculatedAmountField = calculatedAmountField;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNT_NUM
	 * @return  the value of SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNT_NUM
	 * @mbggenerated
	 */
	public String getAccountNum() {
		return accountNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNT_NUM
	 * @param accountNum  the value for SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNT_NUM
	 * @mbggenerated
	 */
	public void setAccountNum(String accountNum) {
		this.accountNum = accountNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNT_DIR
	 * @return  the value of SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNT_DIR
	 * @mbggenerated
	 */
	public String getAccountDir() {
		return accountDir;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNT_DIR
	 * @param accountDir  the value for SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNT_DIR
	 * @mbggenerated
	 */
	public void setAccountDir(String accountDir) {
		this.accountDir = accountDir;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.SUBJECT_NUM
	 * @return  the value of SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.SUBJECT_NUM
	 * @mbggenerated
	 */
	public String getSubjectNum() {
		return subjectNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.SUBJECT_NUM
	 * @param subjectNum  the value for SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.SUBJECT_NUM
	 * @mbggenerated
	 */
	public void setSubjectNum(String subjectNum) {
		this.subjectNum = subjectNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNTING_SUB
	 * @return  the value of SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNTING_SUB
	 * @mbggenerated
	 */
	public String getAccountingSub() {
		return accountingSub;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNTING_SUB
	 * @param accountingSub  the value for SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNTING_SUB
	 * @mbggenerated
	 */
	public void setAccountingSub(String accountingSub) {
		this.accountingSub = accountingSub;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNTING_AUX1
	 * @return  the value of SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNTING_AUX1
	 * @mbggenerated
	 */
	public String getAccountingAux1() {
		return accountingAux1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNTING_AUX1
	 * @param accountingAux1  the value for SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNTING_AUX1
	 * @mbggenerated
	 */
	public void setAccountingAux1(String accountingAux1) {
		this.accountingAux1 = accountingAux1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNTING_AUX2
	 * @return  the value of SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNTING_AUX2
	 * @mbggenerated
	 */
	public String getAccountingAux2() {
		return accountingAux2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNTING_AUX2
	 * @param accountingAux2  the value for SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNTING_AUX2
	 * @mbggenerated
	 */
	public void setAccountingAux2(String accountingAux2) {
		this.accountingAux2 = accountingAux2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNTING_AUX3
	 * @return  the value of SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNTING_AUX3
	 * @mbggenerated
	 */
	public String getAccountingAux3() {
		return accountingAux3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNTING_AUX3
	 * @param accountingAux3  the value for SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNTING_AUX3
	 * @mbggenerated
	 */
	public void setAccountingAux3(String accountingAux3) {
		this.accountingAux3 = accountingAux3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNTING_ABS
	 * @return  the value of SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNTING_ABS
	 * @mbggenerated
	 */
	public String getAccountingAbs() {
		return accountingAbs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNTING_ABS
	 * @param accountingAbs  the value for SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.ACCOUNTING_ABS
	 * @mbggenerated
	 */
	public void setAccountingAbs(String accountingAbs) {
		this.accountingAbs = accountingAbs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.MODEL_NO
	 * @return  the value of SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.MODEL_NO
	 * @mbggenerated
	 */
	public String getModelNo() {
		return modelNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.MODEL_NO
	 * @param modelNo  the value for SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.MODEL_NO
	 * @mbggenerated
	 */
	public void setModelNo(String modelNo) {
		this.modelNo = modelNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.CREATE_TIME
	 * @return  the value of SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.CREATE_TIME
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.CREATE_TIME
	 * @param createTime  the value for SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.CREATE_TIME
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.UPDATE_TIME
	 * @return  the value of SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.UPDATE_TIME
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.UPDATE_TIME
	 * @param updateTime  the value for SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO.UPDATE_TIME
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}