package com.billionsfinance.bas.entity.voucher.model;

import java.util.ArrayList;
import java.util.List;

public class CwVoucherFactResultExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT
     *
     * @mbggenerated
     */
    public CwVoucherFactResultExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAccountingDateIsNull() {
            addCriterion("ACCOUNTING_DATE is null");
            return (Criteria) this;
        }

        public Criteria andAccountingDateIsNotNull() {
            addCriterion("ACCOUNTING_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andAccountingDateEqualTo(String value) {
            addCriterion("ACCOUNTING_DATE =", value, "accountingDate");
            return (Criteria) this;
        }

        public Criteria andAccountingDateNotEqualTo(String value) {
            addCriterion("ACCOUNTING_DATE <>", value, "accountingDate");
            return (Criteria) this;
        }

        public Criteria andAccountingDateGreaterThan(String value) {
            addCriterion("ACCOUNTING_DATE >", value, "accountingDate");
            return (Criteria) this;
        }

        public Criteria andAccountingDateGreaterThanOrEqualTo(String value) {
            addCriterion("ACCOUNTING_DATE >=", value, "accountingDate");
            return (Criteria) this;
        }

        public Criteria andAccountingDateLessThan(String value) {
            addCriterion("ACCOUNTING_DATE <", value, "accountingDate");
            return (Criteria) this;
        }

        public Criteria andAccountingDateLessThanOrEqualTo(String value) {
            addCriterion("ACCOUNTING_DATE <=", value, "accountingDate");
            return (Criteria) this;
        }

        public Criteria andAccountingDateLike(String value) {
            addCriterion("ACCOUNTING_DATE like", value, "accountingDate");
            return (Criteria) this;
        }

        public Criteria andAccountingDateNotLike(String value) {
            addCriterion("ACCOUNTING_DATE not like", value, "accountingDate");
            return (Criteria) this;
        }

        public Criteria andAccountingDateIn(List<String> values) {
            addCriterion("ACCOUNTING_DATE in", values, "accountingDate");
            return (Criteria) this;
        }

        public Criteria andAccountingDateNotIn(List<String> values) {
            addCriterion("ACCOUNTING_DATE not in", values, "accountingDate");
            return (Criteria) this;
        }

        public Criteria andAccountingDateBetween(String value1, String value2) {
            addCriterion("ACCOUNTING_DATE between", value1, value2, "accountingDate");
            return (Criteria) this;
        }

        public Criteria andAccountingDateNotBetween(String value1, String value2) {
            addCriterion("ACCOUNTING_DATE not between", value1, value2, "accountingDate");
            return (Criteria) this;
        }

        public Criteria andDuedateIsNull() {
            addCriterion("DUEDATE is null");
            return (Criteria) this;
        }

        public Criteria andDuedateIsNotNull() {
            addCriterion("DUEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andDuedateEqualTo(String value) {
            addCriterion("DUEDATE =", value, "duedate");
            return (Criteria) this;
        }

        public Criteria andDuedateNotEqualTo(String value) {
            addCriterion("DUEDATE <>", value, "duedate");
            return (Criteria) this;
        }

        public Criteria andDuedateGreaterThan(String value) {
            addCriterion("DUEDATE >", value, "duedate");
            return (Criteria) this;
        }

        public Criteria andDuedateGreaterThanOrEqualTo(String value) {
            addCriterion("DUEDATE >=", value, "duedate");
            return (Criteria) this;
        }

        public Criteria andDuedateLessThan(String value) {
            addCriterion("DUEDATE <", value, "duedate");
            return (Criteria) this;
        }

        public Criteria andDuedateLessThanOrEqualTo(String value) {
            addCriterion("DUEDATE <=", value, "duedate");
            return (Criteria) this;
        }

        public Criteria andDuedateLike(String value) {
            addCriterion("DUEDATE like", value, "duedate");
            return (Criteria) this;
        }

        public Criteria andDuedateNotLike(String value) {
            addCriterion("DUEDATE not like", value, "duedate");
            return (Criteria) this;
        }

        public Criteria andDuedateIn(List<String> values) {
            addCriterion("DUEDATE in", values, "duedate");
            return (Criteria) this;
        }

        public Criteria andDuedateNotIn(List<String> values) {
            addCriterion("DUEDATE not in", values, "duedate");
            return (Criteria) this;
        }

        public Criteria andDuedateBetween(String value1, String value2) {
            addCriterion("DUEDATE between", value1, value2, "duedate");
            return (Criteria) this;
        }

        public Criteria andDuedateNotBetween(String value1, String value2) {
            addCriterion("DUEDATE not between", value1, value2, "duedate");
            return (Criteria) this;
        }

        public Criteria andCustomerDirIsNull() {
            addCriterion("CUSTOMER_DIR is null");
            return (Criteria) this;
        }

        public Criteria andCustomerDirIsNotNull() {
            addCriterion("CUSTOMER_DIR is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerDirEqualTo(String value) {
            addCriterion("CUSTOMER_DIR =", value, "customerDir");
            return (Criteria) this;
        }

        public Criteria andCustomerDirNotEqualTo(String value) {
            addCriterion("CUSTOMER_DIR <>", value, "customerDir");
            return (Criteria) this;
        }

        public Criteria andCustomerDirGreaterThan(String value) {
            addCriterion("CUSTOMER_DIR >", value, "customerDir");
            return (Criteria) this;
        }

        public Criteria andCustomerDirGreaterThanOrEqualTo(String value) {
            addCriterion("CUSTOMER_DIR >=", value, "customerDir");
            return (Criteria) this;
        }

        public Criteria andCustomerDirLessThan(String value) {
            addCriterion("CUSTOMER_DIR <", value, "customerDir");
            return (Criteria) this;
        }

        public Criteria andCustomerDirLessThanOrEqualTo(String value) {
            addCriterion("CUSTOMER_DIR <=", value, "customerDir");
            return (Criteria) this;
        }

        public Criteria andCustomerDirLike(String value) {
            addCriterion("CUSTOMER_DIR like", value, "customerDir");
            return (Criteria) this;
        }

        public Criteria andCustomerDirNotLike(String value) {
            addCriterion("CUSTOMER_DIR not like", value, "customerDir");
            return (Criteria) this;
        }

        public Criteria andCustomerDirIn(List<String> values) {
            addCriterion("CUSTOMER_DIR in", values, "customerDir");
            return (Criteria) this;
        }

        public Criteria andCustomerDirNotIn(List<String> values) {
            addCriterion("CUSTOMER_DIR not in", values, "customerDir");
            return (Criteria) this;
        }

        public Criteria andCustomerDirBetween(String value1, String value2) {
            addCriterion("CUSTOMER_DIR between", value1, value2, "customerDir");
            return (Criteria) this;
        }

        public Criteria andCustomerDirNotBetween(String value1, String value2) {
            addCriterion("CUSTOMER_DIR not between", value1, value2, "customerDir");
            return (Criteria) this;
        }

        public Criteria andBusinessmodelIsNull() {
            addCriterion("BUSINESSMODEL is null");
            return (Criteria) this;
        }

        public Criteria andBusinessmodelIsNotNull() {
            addCriterion("BUSINESSMODEL is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessmodelEqualTo(String value) {
            addCriterion("BUSINESSMODEL =", value, "businessmodel");
            return (Criteria) this;
        }

        public Criteria andBusinessmodelNotEqualTo(String value) {
            addCriterion("BUSINESSMODEL <>", value, "businessmodel");
            return (Criteria) this;
        }

        public Criteria andBusinessmodelGreaterThan(String value) {
            addCriterion("BUSINESSMODEL >", value, "businessmodel");
            return (Criteria) this;
        }

        public Criteria andBusinessmodelGreaterThanOrEqualTo(String value) {
            addCriterion("BUSINESSMODEL >=", value, "businessmodel");
            return (Criteria) this;
        }

        public Criteria andBusinessmodelLessThan(String value) {
            addCriterion("BUSINESSMODEL <", value, "businessmodel");
            return (Criteria) this;
        }

        public Criteria andBusinessmodelLessThanOrEqualTo(String value) {
            addCriterion("BUSINESSMODEL <=", value, "businessmodel");
            return (Criteria) this;
        }

        public Criteria andBusinessmodelLike(String value) {
            addCriterion("BUSINESSMODEL like", value, "businessmodel");
            return (Criteria) this;
        }

        public Criteria andBusinessmodelNotLike(String value) {
            addCriterion("BUSINESSMODEL not like", value, "businessmodel");
            return (Criteria) this;
        }

        public Criteria andBusinessmodelIn(List<String> values) {
            addCriterion("BUSINESSMODEL in", values, "businessmodel");
            return (Criteria) this;
        }

        public Criteria andBusinessmodelNotIn(List<String> values) {
            addCriterion("BUSINESSMODEL not in", values, "businessmodel");
            return (Criteria) this;
        }

        public Criteria andBusinessmodelBetween(String value1, String value2) {
            addCriterion("BUSINESSMODEL between", value1, value2, "businessmodel");
            return (Criteria) this;
        }

        public Criteria andBusinessmodelNotBetween(String value1, String value2) {
            addCriterion("BUSINESSMODEL not between", value1, value2, "businessmodel");
            return (Criteria) this;
        }

        public Criteria andSubproducttypeIsNull() {
            addCriterion("SUBPRODUCTTYPE is null");
            return (Criteria) this;
        }

        public Criteria andSubproducttypeIsNotNull() {
            addCriterion("SUBPRODUCTTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSubproducttypeEqualTo(String value) {
            addCriterion("SUBPRODUCTTYPE =", value, "subproducttype");
            return (Criteria) this;
        }

        public Criteria andSubproducttypeNotEqualTo(String value) {
            addCriterion("SUBPRODUCTTYPE <>", value, "subproducttype");
            return (Criteria) this;
        }

        public Criteria andSubproducttypeGreaterThan(String value) {
            addCriterion("SUBPRODUCTTYPE >", value, "subproducttype");
            return (Criteria) this;
        }

        public Criteria andSubproducttypeGreaterThanOrEqualTo(String value) {
            addCriterion("SUBPRODUCTTYPE >=", value, "subproducttype");
            return (Criteria) this;
        }

        public Criteria andSubproducttypeLessThan(String value) {
            addCriterion("SUBPRODUCTTYPE <", value, "subproducttype");
            return (Criteria) this;
        }

        public Criteria andSubproducttypeLessThanOrEqualTo(String value) {
            addCriterion("SUBPRODUCTTYPE <=", value, "subproducttype");
            return (Criteria) this;
        }

        public Criteria andSubproducttypeLike(String value) {
            addCriterion("SUBPRODUCTTYPE like", value, "subproducttype");
            return (Criteria) this;
        }

        public Criteria andSubproducttypeNotLike(String value) {
            addCriterion("SUBPRODUCTTYPE not like", value, "subproducttype");
            return (Criteria) this;
        }

        public Criteria andSubproducttypeIn(List<String> values) {
            addCriterion("SUBPRODUCTTYPE in", values, "subproducttype");
            return (Criteria) this;
        }

        public Criteria andSubproducttypeNotIn(List<String> values) {
            addCriterion("SUBPRODUCTTYPE not in", values, "subproducttype");
            return (Criteria) this;
        }

        public Criteria andSubproducttypeBetween(String value1, String value2) {
            addCriterion("SUBPRODUCTTYPE between", value1, value2, "subproducttype");
            return (Criteria) this;
        }

        public Criteria andSubproducttypeNotBetween(String value1, String value2) {
            addCriterion("SUBPRODUCTTYPE not between", value1, value2, "subproducttype");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNull() {
            addCriterion("PROVINCE is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("PROVINCE is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceEqualTo(String value) {
            addCriterion("PROVINCE =", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotEqualTo(String value) {
            addCriterion("PROVINCE <>", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThan(String value) {
            addCriterion("PROVINCE >", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("PROVINCE >=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThan(String value) {
            addCriterion("PROVINCE <", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThanOrEqualTo(String value) {
            addCriterion("PROVINCE <=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLike(String value) {
            addCriterion("PROVINCE like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotLike(String value) {
            addCriterion("PROVINCE not like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceIn(List<String> values) {
            addCriterion("PROVINCE in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotIn(List<String> values) {
            addCriterion("PROVINCE not in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceBetween(String value1, String value2) {
            addCriterion("PROVINCE between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotBetween(String value1, String value2) {
            addCriterion("PROVINCE not between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("CITY is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("CITY is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("CITY =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("CITY <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("CITY >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("CITY >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("CITY <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("CITY <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("CITY like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("CITY not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("CITY in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("CITY not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("CITY between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("CITY not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCitycodeIsNull() {
            addCriterion("CITYCODE is null");
            return (Criteria) this;
        }

        public Criteria andCitycodeIsNotNull() {
            addCriterion("CITYCODE is not null");
            return (Criteria) this;
        }

        public Criteria andCitycodeEqualTo(String value) {
            addCriterion("CITYCODE =", value, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeNotEqualTo(String value) {
            addCriterion("CITYCODE <>", value, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeGreaterThan(String value) {
            addCriterion("CITYCODE >", value, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeGreaterThanOrEqualTo(String value) {
            addCriterion("CITYCODE >=", value, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeLessThan(String value) {
            addCriterion("CITYCODE <", value, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeLessThanOrEqualTo(String value) {
            addCriterion("CITYCODE <=", value, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeLike(String value) {
            addCriterion("CITYCODE like", value, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeNotLike(String value) {
            addCriterion("CITYCODE not like", value, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeIn(List<String> values) {
            addCriterion("CITYCODE in", values, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeNotIn(List<String> values) {
            addCriterion("CITYCODE not in", values, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeBetween(String value1, String value2) {
            addCriterion("CITYCODE between", value1, value2, "citycode");
            return (Criteria) this;
        }

        public Criteria andCitycodeNotBetween(String value1, String value2) {
            addCriterion("CITYCODE not between", value1, value2, "citycode");
            return (Criteria) this;
        }

        public Criteria andCanceltypeIsNull() {
            addCriterion("CANCELTYPE is null");
            return (Criteria) this;
        }

        public Criteria andCanceltypeIsNotNull() {
            addCriterion("CANCELTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCanceltypeEqualTo(String value) {
            addCriterion("CANCELTYPE =", value, "canceltype");
            return (Criteria) this;
        }

        public Criteria andCanceltypeNotEqualTo(String value) {
            addCriterion("CANCELTYPE <>", value, "canceltype");
            return (Criteria) this;
        }

        public Criteria andCanceltypeGreaterThan(String value) {
            addCriterion("CANCELTYPE >", value, "canceltype");
            return (Criteria) this;
        }

        public Criteria andCanceltypeGreaterThanOrEqualTo(String value) {
            addCriterion("CANCELTYPE >=", value, "canceltype");
            return (Criteria) this;
        }

        public Criteria andCanceltypeLessThan(String value) {
            addCriterion("CANCELTYPE <", value, "canceltype");
            return (Criteria) this;
        }

        public Criteria andCanceltypeLessThanOrEqualTo(String value) {
            addCriterion("CANCELTYPE <=", value, "canceltype");
            return (Criteria) this;
        }

        public Criteria andCanceltypeLike(String value) {
            addCriterion("CANCELTYPE like", value, "canceltype");
            return (Criteria) this;
        }

        public Criteria andCanceltypeNotLike(String value) {
            addCriterion("CANCELTYPE not like", value, "canceltype");
            return (Criteria) this;
        }

        public Criteria andCanceltypeIn(List<String> values) {
            addCriterion("CANCELTYPE in", values, "canceltype");
            return (Criteria) this;
        }

        public Criteria andCanceltypeNotIn(List<String> values) {
            addCriterion("CANCELTYPE not in", values, "canceltype");
            return (Criteria) this;
        }

        public Criteria andCanceltypeBetween(String value1, String value2) {
            addCriterion("CANCELTYPE between", value1, value2, "canceltype");
            return (Criteria) this;
        }

        public Criteria andCanceltypeNotBetween(String value1, String value2) {
            addCriterion("CANCELTYPE not between", value1, value2, "canceltype");
            return (Criteria) this;
        }

        public Criteria andPaytypeIsNull() {
            addCriterion("PAYTYPE is null");
            return (Criteria) this;
        }

        public Criteria andPaytypeIsNotNull() {
            addCriterion("PAYTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andPaytypeEqualTo(String value) {
            addCriterion("PAYTYPE =", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeNotEqualTo(String value) {
            addCriterion("PAYTYPE <>", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeGreaterThan(String value) {
            addCriterion("PAYTYPE >", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeGreaterThanOrEqualTo(String value) {
            addCriterion("PAYTYPE >=", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeLessThan(String value) {
            addCriterion("PAYTYPE <", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeLessThanOrEqualTo(String value) {
            addCriterion("PAYTYPE <=", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeLike(String value) {
            addCriterion("PAYTYPE like", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeNotLike(String value) {
            addCriterion("PAYTYPE not like", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeIn(List<String> values) {
            addCriterion("PAYTYPE in", values, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeNotIn(List<String> values) {
            addCriterion("PAYTYPE not in", values, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeBetween(String value1, String value2) {
            addCriterion("PAYTYPE between", value1, value2, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeNotBetween(String value1, String value2) {
            addCriterion("PAYTYPE not between", value1, value2, "paytype");
            return (Criteria) this;
        }

        public Criteria andClassfyIsNull() {
            addCriterion("CLASSFY is null");
            return (Criteria) this;
        }

        public Criteria andClassfyIsNotNull() {
            addCriterion("CLASSFY is not null");
            return (Criteria) this;
        }

        public Criteria andClassfyEqualTo(String value) {
            addCriterion("CLASSFY =", value, "classfy");
            return (Criteria) this;
        }

        public Criteria andClassfyNotEqualTo(String value) {
            addCriterion("CLASSFY <>", value, "classfy");
            return (Criteria) this;
        }

        public Criteria andClassfyGreaterThan(String value) {
            addCriterion("CLASSFY >", value, "classfy");
            return (Criteria) this;
        }

        public Criteria andClassfyGreaterThanOrEqualTo(String value) {
            addCriterion("CLASSFY >=", value, "classfy");
            return (Criteria) this;
        }

        public Criteria andClassfyLessThan(String value) {
            addCriterion("CLASSFY <", value, "classfy");
            return (Criteria) this;
        }

        public Criteria andClassfyLessThanOrEqualTo(String value) {
            addCriterion("CLASSFY <=", value, "classfy");
            return (Criteria) this;
        }

        public Criteria andClassfyLike(String value) {
            addCriterion("CLASSFY like", value, "classfy");
            return (Criteria) this;
        }

        public Criteria andClassfyNotLike(String value) {
            addCriterion("CLASSFY not like", value, "classfy");
            return (Criteria) this;
        }

        public Criteria andClassfyIn(List<String> values) {
            addCriterion("CLASSFY in", values, "classfy");
            return (Criteria) this;
        }

        public Criteria andClassfyNotIn(List<String> values) {
            addCriterion("CLASSFY not in", values, "classfy");
            return (Criteria) this;
        }

        public Criteria andClassfyBetween(String value1, String value2) {
            addCriterion("CLASSFY between", value1, value2, "classfy");
            return (Criteria) this;
        }

        public Criteria andClassfyNotBetween(String value1, String value2) {
            addCriterion("CLASSFY not between", value1, value2, "classfy");
            return (Criteria) this;
        }

        public Criteria andDeliverydateIsNull() {
            addCriterion("DELIVERYDATE is null");
            return (Criteria) this;
        }

        public Criteria andDeliverydateIsNotNull() {
            addCriterion("DELIVERYDATE is not null");
            return (Criteria) this;
        }

        public Criteria andDeliverydateEqualTo(String value) {
            addCriterion("DELIVERYDATE =", value, "deliverydate");
            return (Criteria) this;
        }

        public Criteria andDeliverydateNotEqualTo(String value) {
            addCriterion("DELIVERYDATE <>", value, "deliverydate");
            return (Criteria) this;
        }

        public Criteria andDeliverydateGreaterThan(String value) {
            addCriterion("DELIVERYDATE >", value, "deliverydate");
            return (Criteria) this;
        }

        public Criteria andDeliverydateGreaterThanOrEqualTo(String value) {
            addCriterion("DELIVERYDATE >=", value, "deliverydate");
            return (Criteria) this;
        }

        public Criteria andDeliverydateLessThan(String value) {
            addCriterion("DELIVERYDATE <", value, "deliverydate");
            return (Criteria) this;
        }

        public Criteria andDeliverydateLessThanOrEqualTo(String value) {
            addCriterion("DELIVERYDATE <=", value, "deliverydate");
            return (Criteria) this;
        }

        public Criteria andDeliverydateLike(String value) {
            addCriterion("DELIVERYDATE like", value, "deliverydate");
            return (Criteria) this;
        }

        public Criteria andDeliverydateNotLike(String value) {
            addCriterion("DELIVERYDATE not like", value, "deliverydate");
            return (Criteria) this;
        }

        public Criteria andDeliverydateIn(List<String> values) {
            addCriterion("DELIVERYDATE in", values, "deliverydate");
            return (Criteria) this;
        }

        public Criteria andDeliverydateNotIn(List<String> values) {
            addCriterion("DELIVERYDATE not in", values, "deliverydate");
            return (Criteria) this;
        }

        public Criteria andDeliverydateBetween(String value1, String value2) {
            addCriterion("DELIVERYDATE between", value1, value2, "deliverydate");
            return (Criteria) this;
        }

        public Criteria andDeliverydateNotBetween(String value1, String value2) {
            addCriterion("DELIVERYDATE not between", value1, value2, "deliverydate");
            return (Criteria) this;
        }

        public Criteria andDcdateIsNull() {
            addCriterion("DCDATE is null");
            return (Criteria) this;
        }

        public Criteria andDcdateIsNotNull() {
            addCriterion("DCDATE is not null");
            return (Criteria) this;
        }

        public Criteria andDcdateEqualTo(String value) {
            addCriterion("DCDATE =", value, "dcdate");
            return (Criteria) this;
        }

        public Criteria andDcdateNotEqualTo(String value) {
            addCriterion("DCDATE <>", value, "dcdate");
            return (Criteria) this;
        }

        public Criteria andDcdateGreaterThan(String value) {
            addCriterion("DCDATE >", value, "dcdate");
            return (Criteria) this;
        }

        public Criteria andDcdateGreaterThanOrEqualTo(String value) {
            addCriterion("DCDATE >=", value, "dcdate");
            return (Criteria) this;
        }

        public Criteria andDcdateLessThan(String value) {
            addCriterion("DCDATE <", value, "dcdate");
            return (Criteria) this;
        }

        public Criteria andDcdateLessThanOrEqualTo(String value) {
            addCriterion("DCDATE <=", value, "dcdate");
            return (Criteria) this;
        }

        public Criteria andDcdateLike(String value) {
            addCriterion("DCDATE like", value, "dcdate");
            return (Criteria) this;
        }

        public Criteria andDcdateNotLike(String value) {
            addCriterion("DCDATE not like", value, "dcdate");
            return (Criteria) this;
        }

        public Criteria andDcdateIn(List<String> values) {
            addCriterion("DCDATE in", values, "dcdate");
            return (Criteria) this;
        }

        public Criteria andDcdateNotIn(List<String> values) {
            addCriterion("DCDATE not in", values, "dcdate");
            return (Criteria) this;
        }

        public Criteria andDcdateBetween(String value1, String value2) {
            addCriterion("DCDATE between", value1, value2, "dcdate");
            return (Criteria) this;
        }

        public Criteria andDcdateNotBetween(String value1, String value2) {
            addCriterion("DCDATE not between", value1, value2, "dcdate");
            return (Criteria) this;
        }

        public Criteria andShdateIsNull() {
            addCriterion("SHDATE is null");
            return (Criteria) this;
        }

        public Criteria andShdateIsNotNull() {
            addCriterion("SHDATE is not null");
            return (Criteria) this;
        }

        public Criteria andShdateEqualTo(String value) {
            addCriterion("SHDATE =", value, "shdate");
            return (Criteria) this;
        }

        public Criteria andShdateNotEqualTo(String value) {
            addCriterion("SHDATE <>", value, "shdate");
            return (Criteria) this;
        }

        public Criteria andShdateGreaterThan(String value) {
            addCriterion("SHDATE >", value, "shdate");
            return (Criteria) this;
        }

        public Criteria andShdateGreaterThanOrEqualTo(String value) {
            addCriterion("SHDATE >=", value, "shdate");
            return (Criteria) this;
        }

        public Criteria andShdateLessThan(String value) {
            addCriterion("SHDATE <", value, "shdate");
            return (Criteria) this;
        }

        public Criteria andShdateLessThanOrEqualTo(String value) {
            addCriterion("SHDATE <=", value, "shdate");
            return (Criteria) this;
        }

        public Criteria andShdateLike(String value) {
            addCriterion("SHDATE like", value, "shdate");
            return (Criteria) this;
        }

        public Criteria andShdateNotLike(String value) {
            addCriterion("SHDATE not like", value, "shdate");
            return (Criteria) this;
        }

        public Criteria andShdateIn(List<String> values) {
            addCriterion("SHDATE in", values, "shdate");
            return (Criteria) this;
        }

        public Criteria andShdateNotIn(List<String> values) {
            addCriterion("SHDATE not in", values, "shdate");
            return (Criteria) this;
        }

        public Criteria andShdateBetween(String value1, String value2) {
            addCriterion("SHDATE between", value1, value2, "shdate");
            return (Criteria) this;
        }

        public Criteria andShdateNotBetween(String value1, String value2) {
            addCriterion("SHDATE not between", value1, value2, "shdate");
            return (Criteria) this;
        }

        public Criteria andLpdateIsNull() {
            addCriterion("LPDATE is null");
            return (Criteria) this;
        }

        public Criteria andLpdateIsNotNull() {
            addCriterion("LPDATE is not null");
            return (Criteria) this;
        }

        public Criteria andLpdateEqualTo(String value) {
            addCriterion("LPDATE =", value, "lpdate");
            return (Criteria) this;
        }

        public Criteria andLpdateNotEqualTo(String value) {
            addCriterion("LPDATE <>", value, "lpdate");
            return (Criteria) this;
        }

        public Criteria andLpdateGreaterThan(String value) {
            addCriterion("LPDATE >", value, "lpdate");
            return (Criteria) this;
        }

        public Criteria andLpdateGreaterThanOrEqualTo(String value) {
            addCriterion("LPDATE >=", value, "lpdate");
            return (Criteria) this;
        }

        public Criteria andLpdateLessThan(String value) {
            addCriterion("LPDATE <", value, "lpdate");
            return (Criteria) this;
        }

        public Criteria andLpdateLessThanOrEqualTo(String value) {
            addCriterion("LPDATE <=", value, "lpdate");
            return (Criteria) this;
        }

        public Criteria andLpdateLike(String value) {
            addCriterion("LPDATE like", value, "lpdate");
            return (Criteria) this;
        }

        public Criteria andLpdateNotLike(String value) {
            addCriterion("LPDATE not like", value, "lpdate");
            return (Criteria) this;
        }

        public Criteria andLpdateIn(List<String> values) {
            addCriterion("LPDATE in", values, "lpdate");
            return (Criteria) this;
        }

        public Criteria andLpdateNotIn(List<String> values) {
            addCriterion("LPDATE not in", values, "lpdate");
            return (Criteria) this;
        }

        public Criteria andLpdateBetween(String value1, String value2) {
            addCriterion("LPDATE between", value1, value2, "lpdate");
            return (Criteria) this;
        }

        public Criteria andLpdateNotBetween(String value1, String value2) {
            addCriterion("LPDATE not between", value1, value2, "lpdate");
            return (Criteria) this;
        }

        public Criteria andDeboursIsNull() {
            addCriterion("DEBOURS is null");
            return (Criteria) this;
        }

        public Criteria andDeboursIsNotNull() {
            addCriterion("DEBOURS is not null");
            return (Criteria) this;
        }

        public Criteria andDeboursEqualTo(String value) {
            addCriterion("DEBOURS =", value, "debours");
            return (Criteria) this;
        }

        public Criteria andDeboursNotEqualTo(String value) {
            addCriterion("DEBOURS <>", value, "debours");
            return (Criteria) this;
        }

        public Criteria andDeboursGreaterThan(String value) {
            addCriterion("DEBOURS >", value, "debours");
            return (Criteria) this;
        }

        public Criteria andDeboursGreaterThanOrEqualTo(String value) {
            addCriterion("DEBOURS >=", value, "debours");
            return (Criteria) this;
        }

        public Criteria andDeboursLessThan(String value) {
            addCriterion("DEBOURS <", value, "debours");
            return (Criteria) this;
        }

        public Criteria andDeboursLessThanOrEqualTo(String value) {
            addCriterion("DEBOURS <=", value, "debours");
            return (Criteria) this;
        }

        public Criteria andDeboursLike(String value) {
            addCriterion("DEBOURS like", value, "debours");
            return (Criteria) this;
        }

        public Criteria andDeboursNotLike(String value) {
            addCriterion("DEBOURS not like", value, "debours");
            return (Criteria) this;
        }

        public Criteria andDeboursIn(List<String> values) {
            addCriterion("DEBOURS in", values, "debours");
            return (Criteria) this;
        }

        public Criteria andDeboursNotIn(List<String> values) {
            addCriterion("DEBOURS not in", values, "debours");
            return (Criteria) this;
        }

        public Criteria andDeboursBetween(String value1, String value2) {
            addCriterion("DEBOURS between", value1, value2, "debours");
            return (Criteria) this;
        }

        public Criteria andDeboursNotBetween(String value1, String value2) {
            addCriterion("DEBOURS not between", value1, value2, "debours");
            return (Criteria) this;
        }

        public Criteria andAssetbelongIsNull() {
            addCriterion("ASSETBELONG is null");
            return (Criteria) this;
        }

        public Criteria andAssetbelongIsNotNull() {
            addCriterion("ASSETBELONG is not null");
            return (Criteria) this;
        }

        public Criteria andAssetbelongEqualTo(String value) {
            addCriterion("ASSETBELONG =", value, "assetbelong");
            return (Criteria) this;
        }

        public Criteria andAssetbelongNotEqualTo(String value) {
            addCriterion("ASSETBELONG <>", value, "assetbelong");
            return (Criteria) this;
        }

        public Criteria andAssetbelongGreaterThan(String value) {
            addCriterion("ASSETBELONG >", value, "assetbelong");
            return (Criteria) this;
        }

        public Criteria andAssetbelongGreaterThanOrEqualTo(String value) {
            addCriterion("ASSETBELONG >=", value, "assetbelong");
            return (Criteria) this;
        }

        public Criteria andAssetbelongLessThan(String value) {
            addCriterion("ASSETBELONG <", value, "assetbelong");
            return (Criteria) this;
        }

        public Criteria andAssetbelongLessThanOrEqualTo(String value) {
            addCriterion("ASSETBELONG <=", value, "assetbelong");
            return (Criteria) this;
        }

        public Criteria andAssetbelongLike(String value) {
            addCriterion("ASSETBELONG like", value, "assetbelong");
            return (Criteria) this;
        }

        public Criteria andAssetbelongNotLike(String value) {
            addCriterion("ASSETBELONG not like", value, "assetbelong");
            return (Criteria) this;
        }

        public Criteria andAssetbelongIn(List<String> values) {
            addCriterion("ASSETBELONG in", values, "assetbelong");
            return (Criteria) this;
        }

        public Criteria andAssetbelongNotIn(List<String> values) {
            addCriterion("ASSETBELONG not in", values, "assetbelong");
            return (Criteria) this;
        }

        public Criteria andAssetbelongBetween(String value1, String value2) {
            addCriterion("ASSETBELONG between", value1, value2, "assetbelong");
            return (Criteria) this;
        }

        public Criteria andAssetbelongNotBetween(String value1, String value2) {
            addCriterion("ASSETBELONG not between", value1, value2, "assetbelong");
            return (Criteria) this;
        }

        public Criteria andGuaranteepartyIsNull() {
            addCriterion("GUARANTEEPARTY is null");
            return (Criteria) this;
        }

        public Criteria andGuaranteepartyIsNotNull() {
            addCriterion("GUARANTEEPARTY is not null");
            return (Criteria) this;
        }

        public Criteria andGuaranteepartyEqualTo(String value) {
            addCriterion("GUARANTEEPARTY =", value, "guaranteeparty");
            return (Criteria) this;
        }

        public Criteria andGuaranteepartyNotEqualTo(String value) {
            addCriterion("GUARANTEEPARTY <>", value, "guaranteeparty");
            return (Criteria) this;
        }

        public Criteria andGuaranteepartyGreaterThan(String value) {
            addCriterion("GUARANTEEPARTY >", value, "guaranteeparty");
            return (Criteria) this;
        }

        public Criteria andGuaranteepartyGreaterThanOrEqualTo(String value) {
            addCriterion("GUARANTEEPARTY >=", value, "guaranteeparty");
            return (Criteria) this;
        }

        public Criteria andGuaranteepartyLessThan(String value) {
            addCriterion("GUARANTEEPARTY <", value, "guaranteeparty");
            return (Criteria) this;
        }

        public Criteria andGuaranteepartyLessThanOrEqualTo(String value) {
            addCriterion("GUARANTEEPARTY <=", value, "guaranteeparty");
            return (Criteria) this;
        }

        public Criteria andGuaranteepartyLike(String value) {
            addCriterion("GUARANTEEPARTY like", value, "guaranteeparty");
            return (Criteria) this;
        }

        public Criteria andGuaranteepartyNotLike(String value) {
            addCriterion("GUARANTEEPARTY not like", value, "guaranteeparty");
            return (Criteria) this;
        }

        public Criteria andGuaranteepartyIn(List<String> values) {
            addCriterion("GUARANTEEPARTY in", values, "guaranteeparty");
            return (Criteria) this;
        }

        public Criteria andGuaranteepartyNotIn(List<String> values) {
            addCriterion("GUARANTEEPARTY not in", values, "guaranteeparty");
            return (Criteria) this;
        }

        public Criteria andGuaranteepartyBetween(String value1, String value2) {
            addCriterion("GUARANTEEPARTY between", value1, value2, "guaranteeparty");
            return (Criteria) this;
        }

        public Criteria andGuaranteepartyNotBetween(String value1, String value2) {
            addCriterion("GUARANTEEPARTY not between", value1, value2, "guaranteeparty");
            return (Criteria) this;
        }

        public Criteria andSponsorIsNull() {
            addCriterion("SPONSOR is null");
            return (Criteria) this;
        }

        public Criteria andSponsorIsNotNull() {
            addCriterion("SPONSOR is not null");
            return (Criteria) this;
        }

        public Criteria andSponsorEqualTo(String value) {
            addCriterion("SPONSOR =", value, "sponsor");
            return (Criteria) this;
        }

        public Criteria andSponsorNotEqualTo(String value) {
            addCriterion("SPONSOR <>", value, "sponsor");
            return (Criteria) this;
        }

        public Criteria andSponsorGreaterThan(String value) {
            addCriterion("SPONSOR >", value, "sponsor");
            return (Criteria) this;
        }

        public Criteria andSponsorGreaterThanOrEqualTo(String value) {
            addCriterion("SPONSOR >=", value, "sponsor");
            return (Criteria) this;
        }

        public Criteria andSponsorLessThan(String value) {
            addCriterion("SPONSOR <", value, "sponsor");
            return (Criteria) this;
        }

        public Criteria andSponsorLessThanOrEqualTo(String value) {
            addCriterion("SPONSOR <=", value, "sponsor");
            return (Criteria) this;
        }

        public Criteria andSponsorLike(String value) {
            addCriterion("SPONSOR like", value, "sponsor");
            return (Criteria) this;
        }

        public Criteria andSponsorNotLike(String value) {
            addCriterion("SPONSOR not like", value, "sponsor");
            return (Criteria) this;
        }

        public Criteria andSponsorIn(List<String> values) {
            addCriterion("SPONSOR in", values, "sponsor");
            return (Criteria) this;
        }

        public Criteria andSponsorNotIn(List<String> values) {
            addCriterion("SPONSOR not in", values, "sponsor");
            return (Criteria) this;
        }

        public Criteria andSponsorBetween(String value1, String value2) {
            addCriterion("SPONSOR between", value1, value2, "sponsor");
            return (Criteria) this;
        }

        public Criteria andSponsorNotBetween(String value1, String value2) {
            addCriterion("SPONSOR not between", value1, value2, "sponsor");
            return (Criteria) this;
        }

        public Criteria andSponsortypeIsNull() {
            addCriterion("SPONSORTYPE is null");
            return (Criteria) this;
        }

        public Criteria andSponsortypeIsNotNull() {
            addCriterion("SPONSORTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSponsortypeEqualTo(String value) {
            addCriterion("SPONSORTYPE =", value, "sponsortype");
            return (Criteria) this;
        }

        public Criteria andSponsortypeNotEqualTo(String value) {
            addCriterion("SPONSORTYPE <>", value, "sponsortype");
            return (Criteria) this;
        }

        public Criteria andSponsortypeGreaterThan(String value) {
            addCriterion("SPONSORTYPE >", value, "sponsortype");
            return (Criteria) this;
        }

        public Criteria andSponsortypeGreaterThanOrEqualTo(String value) {
            addCriterion("SPONSORTYPE >=", value, "sponsortype");
            return (Criteria) this;
        }

        public Criteria andSponsortypeLessThan(String value) {
            addCriterion("SPONSORTYPE <", value, "sponsortype");
            return (Criteria) this;
        }

        public Criteria andSponsortypeLessThanOrEqualTo(String value) {
            addCriterion("SPONSORTYPE <=", value, "sponsortype");
            return (Criteria) this;
        }

        public Criteria andSponsortypeLike(String value) {
            addCriterion("SPONSORTYPE like", value, "sponsortype");
            return (Criteria) this;
        }

        public Criteria andSponsortypeNotLike(String value) {
            addCriterion("SPONSORTYPE not like", value, "sponsortype");
            return (Criteria) this;
        }

        public Criteria andSponsortypeIn(List<String> values) {
            addCriterion("SPONSORTYPE in", values, "sponsortype");
            return (Criteria) this;
        }

        public Criteria andSponsortypeNotIn(List<String> values) {
            addCriterion("SPONSORTYPE not in", values, "sponsortype");
            return (Criteria) this;
        }

        public Criteria andSponsortypeBetween(String value1, String value2) {
            addCriterion("SPONSORTYPE between", value1, value2, "sponsortype");
            return (Criteria) this;
        }

        public Criteria andSponsortypeNotBetween(String value1, String value2) {
            addCriterion("SPONSORTYPE not between", value1, value2, "sponsortype");
            return (Criteria) this;
        }

        public Criteria andIsInstalmentsEndIsNull() {
            addCriterion("IS_INSTALMENTS_END is null");
            return (Criteria) this;
        }

        public Criteria andIsInstalmentsEndIsNotNull() {
            addCriterion("IS_INSTALMENTS_END is not null");
            return (Criteria) this;
        }

        public Criteria andIsInstalmentsEndEqualTo(String value) {
            addCriterion("IS_INSTALMENTS_END =", value, "isInstalmentsEnd");
            return (Criteria) this;
        }

        public Criteria andIsInstalmentsEndNotEqualTo(String value) {
            addCriterion("IS_INSTALMENTS_END <>", value, "isInstalmentsEnd");
            return (Criteria) this;
        }

        public Criteria andIsInstalmentsEndGreaterThan(String value) {
            addCriterion("IS_INSTALMENTS_END >", value, "isInstalmentsEnd");
            return (Criteria) this;
        }

        public Criteria andIsInstalmentsEndGreaterThanOrEqualTo(String value) {
            addCriterion("IS_INSTALMENTS_END >=", value, "isInstalmentsEnd");
            return (Criteria) this;
        }

        public Criteria andIsInstalmentsEndLessThan(String value) {
            addCriterion("IS_INSTALMENTS_END <", value, "isInstalmentsEnd");
            return (Criteria) this;
        }

        public Criteria andIsInstalmentsEndLessThanOrEqualTo(String value) {
            addCriterion("IS_INSTALMENTS_END <=", value, "isInstalmentsEnd");
            return (Criteria) this;
        }

        public Criteria andIsInstalmentsEndLike(String value) {
            addCriterion("IS_INSTALMENTS_END like", value, "isInstalmentsEnd");
            return (Criteria) this;
        }

        public Criteria andIsInstalmentsEndNotLike(String value) {
            addCriterion("IS_INSTALMENTS_END not like", value, "isInstalmentsEnd");
            return (Criteria) this;
        }

        public Criteria andIsInstalmentsEndIn(List<String> values) {
            addCriterion("IS_INSTALMENTS_END in", values, "isInstalmentsEnd");
            return (Criteria) this;
        }

        public Criteria andIsInstalmentsEndNotIn(List<String> values) {
            addCriterion("IS_INSTALMENTS_END not in", values, "isInstalmentsEnd");
            return (Criteria) this;
        }

        public Criteria andIsInstalmentsEndBetween(String value1, String value2) {
            addCriterion("IS_INSTALMENTS_END between", value1, value2, "isInstalmentsEnd");
            return (Criteria) this;
        }

        public Criteria andIsInstalmentsEndNotBetween(String value1, String value2) {
            addCriterion("IS_INSTALMENTS_END not between", value1, value2, "isInstalmentsEnd");
            return (Criteria) this;
        }

        public Criteria andBxhxdateIsNull() {
            addCriterion("BXHXDATE is null");
            return (Criteria) this;
        }

        public Criteria andBxhxdateIsNotNull() {
            addCriterion("BXHXDATE is not null");
            return (Criteria) this;
        }

        public Criteria andBxhxdateEqualTo(String value) {
            addCriterion("BXHXDATE =", value, "bxhxdate");
            return (Criteria) this;
        }

        public Criteria andBxhxdateNotEqualTo(String value) {
            addCriterion("BXHXDATE <>", value, "bxhxdate");
            return (Criteria) this;
        }

        public Criteria andBxhxdateGreaterThan(String value) {
            addCriterion("BXHXDATE >", value, "bxhxdate");
            return (Criteria) this;
        }

        public Criteria andBxhxdateGreaterThanOrEqualTo(String value) {
            addCriterion("BXHXDATE >=", value, "bxhxdate");
            return (Criteria) this;
        }

        public Criteria andBxhxdateLessThan(String value) {
            addCriterion("BXHXDATE <", value, "bxhxdate");
            return (Criteria) this;
        }

        public Criteria andBxhxdateLessThanOrEqualTo(String value) {
            addCriterion("BXHXDATE <=", value, "bxhxdate");
            return (Criteria) this;
        }

        public Criteria andBxhxdateLike(String value) {
            addCriterion("BXHXDATE like", value, "bxhxdate");
            return (Criteria) this;
        }

        public Criteria andBxhxdateNotLike(String value) {
            addCriterion("BXHXDATE not like", value, "bxhxdate");
            return (Criteria) this;
        }

        public Criteria andBxhxdateIn(List<String> values) {
            addCriterion("BXHXDATE in", values, "bxhxdate");
            return (Criteria) this;
        }

        public Criteria andBxhxdateNotIn(List<String> values) {
            addCriterion("BXHXDATE not in", values, "bxhxdate");
            return (Criteria) this;
        }

        public Criteria andBxhxdateBetween(String value1, String value2) {
            addCriterion("BXHXDATE between", value1, value2, "bxhxdate");
            return (Criteria) this;
        }

        public Criteria andBxhxdateNotBetween(String value1, String value2) {
            addCriterion("BXHXDATE not between", value1, value2, "bxhxdate");
            return (Criteria) this;
        }

        public Criteria andActualpaydateIsNull() {
            addCriterion("ACTUALPAYDATE is null");
            return (Criteria) this;
        }

        public Criteria andActualpaydateIsNotNull() {
            addCriterion("ACTUALPAYDATE is not null");
            return (Criteria) this;
        }

        public Criteria andActualpaydateEqualTo(String value) {
            addCriterion("ACTUALPAYDATE =", value, "actualpaydate");
            return (Criteria) this;
        }

        public Criteria andActualpaydateNotEqualTo(String value) {
            addCriterion("ACTUALPAYDATE <>", value, "actualpaydate");
            return (Criteria) this;
        }

        public Criteria andActualpaydateGreaterThan(String value) {
            addCriterion("ACTUALPAYDATE >", value, "actualpaydate");
            return (Criteria) this;
        }

        public Criteria andActualpaydateGreaterThanOrEqualTo(String value) {
            addCriterion("ACTUALPAYDATE >=", value, "actualpaydate");
            return (Criteria) this;
        }

        public Criteria andActualpaydateLessThan(String value) {
            addCriterion("ACTUALPAYDATE <", value, "actualpaydate");
            return (Criteria) this;
        }

        public Criteria andActualpaydateLessThanOrEqualTo(String value) {
            addCriterion("ACTUALPAYDATE <=", value, "actualpaydate");
            return (Criteria) this;
        }

        public Criteria andActualpaydateLike(String value) {
            addCriterion("ACTUALPAYDATE like", value, "actualpaydate");
            return (Criteria) this;
        }

        public Criteria andActualpaydateNotLike(String value) {
            addCriterion("ACTUALPAYDATE not like", value, "actualpaydate");
            return (Criteria) this;
        }

        public Criteria andActualpaydateIn(List<String> values) {
            addCriterion("ACTUALPAYDATE in", values, "actualpaydate");
            return (Criteria) this;
        }

        public Criteria andActualpaydateNotIn(List<String> values) {
            addCriterion("ACTUALPAYDATE not in", values, "actualpaydate");
            return (Criteria) this;
        }

        public Criteria andActualpaydateBetween(String value1, String value2) {
            addCriterion("ACTUALPAYDATE between", value1, value2, "actualpaydate");
            return (Criteria) this;
        }

        public Criteria andActualpaydateNotBetween(String value1, String value2) {
            addCriterion("ACTUALPAYDATE not between", value1, value2, "actualpaydate");
            return (Criteria) this;
        }

        public Criteria andPayprincipalamtIsNull() {
            addCriterion("PAYPRINCIPALAMT is null");
            return (Criteria) this;
        }

        public Criteria andPayprincipalamtIsNotNull() {
            addCriterion("PAYPRINCIPALAMT is not null");
            return (Criteria) this;
        }

        public Criteria andPayprincipalamtEqualTo(String value) {
            addCriterion("PAYPRINCIPALAMT =", value, "payprincipalamt");
            return (Criteria) this;
        }

        public Criteria andPayprincipalamtNotEqualTo(String value) {
            addCriterion("PAYPRINCIPALAMT <>", value, "payprincipalamt");
            return (Criteria) this;
        }

        public Criteria andPayprincipalamtGreaterThan(String value) {
            addCriterion("PAYPRINCIPALAMT >", value, "payprincipalamt");
            return (Criteria) this;
        }

        public Criteria andPayprincipalamtGreaterThanOrEqualTo(String value) {
            addCriterion("PAYPRINCIPALAMT >=", value, "payprincipalamt");
            return (Criteria) this;
        }

        public Criteria andPayprincipalamtLessThan(String value) {
            addCriterion("PAYPRINCIPALAMT <", value, "payprincipalamt");
            return (Criteria) this;
        }

        public Criteria andPayprincipalamtLessThanOrEqualTo(String value) {
            addCriterion("PAYPRINCIPALAMT <=", value, "payprincipalamt");
            return (Criteria) this;
        }

        public Criteria andPayprincipalamtLike(String value) {
            addCriterion("PAYPRINCIPALAMT like", value, "payprincipalamt");
            return (Criteria) this;
        }

        public Criteria andPayprincipalamtNotLike(String value) {
            addCriterion("PAYPRINCIPALAMT not like", value, "payprincipalamt");
            return (Criteria) this;
        }

        public Criteria andPayprincipalamtIn(List<String> values) {
            addCriterion("PAYPRINCIPALAMT in", values, "payprincipalamt");
            return (Criteria) this;
        }

        public Criteria andPayprincipalamtNotIn(List<String> values) {
            addCriterion("PAYPRINCIPALAMT not in", values, "payprincipalamt");
            return (Criteria) this;
        }

        public Criteria andPayprincipalamtBetween(String value1, String value2) {
            addCriterion("PAYPRINCIPALAMT between", value1, value2, "payprincipalamt");
            return (Criteria) this;
        }

        public Criteria andPayprincipalamtNotBetween(String value1, String value2) {
            addCriterion("PAYPRINCIPALAMT not between", value1, value2, "payprincipalamt");
            return (Criteria) this;
        }

        public Criteria andPayinteamtIsNull() {
            addCriterion("PAYINTEAMT is null");
            return (Criteria) this;
        }

        public Criteria andPayinteamtIsNotNull() {
            addCriterion("PAYINTEAMT is not null");
            return (Criteria) this;
        }

        public Criteria andPayinteamtEqualTo(String value) {
            addCriterion("PAYINTEAMT =", value, "payinteamt");
            return (Criteria) this;
        }

        public Criteria andPayinteamtNotEqualTo(String value) {
            addCriterion("PAYINTEAMT <>", value, "payinteamt");
            return (Criteria) this;
        }

        public Criteria andPayinteamtGreaterThan(String value) {
            addCriterion("PAYINTEAMT >", value, "payinteamt");
            return (Criteria) this;
        }

        public Criteria andPayinteamtGreaterThanOrEqualTo(String value) {
            addCriterion("PAYINTEAMT >=", value, "payinteamt");
            return (Criteria) this;
        }

        public Criteria andPayinteamtLessThan(String value) {
            addCriterion("PAYINTEAMT <", value, "payinteamt");
            return (Criteria) this;
        }

        public Criteria andPayinteamtLessThanOrEqualTo(String value) {
            addCriterion("PAYINTEAMT <=", value, "payinteamt");
            return (Criteria) this;
        }

        public Criteria andPayinteamtLike(String value) {
            addCriterion("PAYINTEAMT like", value, "payinteamt");
            return (Criteria) this;
        }

        public Criteria andPayinteamtNotLike(String value) {
            addCriterion("PAYINTEAMT not like", value, "payinteamt");
            return (Criteria) this;
        }

        public Criteria andPayinteamtIn(List<String> values) {
            addCriterion("PAYINTEAMT in", values, "payinteamt");
            return (Criteria) this;
        }

        public Criteria andPayinteamtNotIn(List<String> values) {
            addCriterion("PAYINTEAMT not in", values, "payinteamt");
            return (Criteria) this;
        }

        public Criteria andPayinteamtBetween(String value1, String value2) {
            addCriterion("PAYINTEAMT between", value1, value2, "payinteamt");
            return (Criteria) this;
        }

        public Criteria andPayinteamtNotBetween(String value1, String value2) {
            addCriterion("PAYINTEAMT not between", value1, value2, "payinteamt");
            return (Criteria) this;
        }

        public Criteria andA2IsNull() {
            addCriterion("A2 is null");
            return (Criteria) this;
        }

        public Criteria andA2IsNotNull() {
            addCriterion("A2 is not null");
            return (Criteria) this;
        }

        public Criteria andA2EqualTo(String value) {
            addCriterion("A2 =", value, "a2");
            return (Criteria) this;
        }

        public Criteria andA2NotEqualTo(String value) {
            addCriterion("A2 <>", value, "a2");
            return (Criteria) this;
        }

        public Criteria andA2GreaterThan(String value) {
            addCriterion("A2 >", value, "a2");
            return (Criteria) this;
        }

        public Criteria andA2GreaterThanOrEqualTo(String value) {
            addCriterion("A2 >=", value, "a2");
            return (Criteria) this;
        }

        public Criteria andA2LessThan(String value) {
            addCriterion("A2 <", value, "a2");
            return (Criteria) this;
        }

        public Criteria andA2LessThanOrEqualTo(String value) {
            addCriterion("A2 <=", value, "a2");
            return (Criteria) this;
        }

        public Criteria andA2Like(String value) {
            addCriterion("A2 like", value, "a2");
            return (Criteria) this;
        }

        public Criteria andA2NotLike(String value) {
            addCriterion("A2 not like", value, "a2");
            return (Criteria) this;
        }

        public Criteria andA2In(List<String> values) {
            addCriterion("A2 in", values, "a2");
            return (Criteria) this;
        }

        public Criteria andA2NotIn(List<String> values) {
            addCriterion("A2 not in", values, "a2");
            return (Criteria) this;
        }

        public Criteria andA2Between(String value1, String value2) {
            addCriterion("A2 between", value1, value2, "a2");
            return (Criteria) this;
        }

        public Criteria andA2NotBetween(String value1, String value2) {
            addCriterion("A2 not between", value1, value2, "a2");
            return (Criteria) this;
        }

        public Criteria andA7IsNull() {
            addCriterion("A7 is null");
            return (Criteria) this;
        }

        public Criteria andA7IsNotNull() {
            addCriterion("A7 is not null");
            return (Criteria) this;
        }

        public Criteria andA7EqualTo(String value) {
            addCriterion("A7 =", value, "a7");
            return (Criteria) this;
        }

        public Criteria andA7NotEqualTo(String value) {
            addCriterion("A7 <>", value, "a7");
            return (Criteria) this;
        }

        public Criteria andA7GreaterThan(String value) {
            addCriterion("A7 >", value, "a7");
            return (Criteria) this;
        }

        public Criteria andA7GreaterThanOrEqualTo(String value) {
            addCriterion("A7 >=", value, "a7");
            return (Criteria) this;
        }

        public Criteria andA7LessThan(String value) {
            addCriterion("A7 <", value, "a7");
            return (Criteria) this;
        }

        public Criteria andA7LessThanOrEqualTo(String value) {
            addCriterion("A7 <=", value, "a7");
            return (Criteria) this;
        }

        public Criteria andA7Like(String value) {
            addCriterion("A7 like", value, "a7");
            return (Criteria) this;
        }

        public Criteria andA7NotLike(String value) {
            addCriterion("A7 not like", value, "a7");
            return (Criteria) this;
        }

        public Criteria andA7In(List<String> values) {
            addCriterion("A7 in", values, "a7");
            return (Criteria) this;
        }

        public Criteria andA7NotIn(List<String> values) {
            addCriterion("A7 not in", values, "a7");
            return (Criteria) this;
        }

        public Criteria andA7Between(String value1, String value2) {
            addCriterion("A7 between", value1, value2, "a7");
            return (Criteria) this;
        }

        public Criteria andA7NotBetween(String value1, String value2) {
            addCriterion("A7 not between", value1, value2, "a7");
            return (Criteria) this;
        }

        public Criteria andA12IsNull() {
            addCriterion("A12 is null");
            return (Criteria) this;
        }

        public Criteria andA12IsNotNull() {
            addCriterion("A12 is not null");
            return (Criteria) this;
        }

        public Criteria andA12EqualTo(String value) {
            addCriterion("A12 =", value, "a12");
            return (Criteria) this;
        }

        public Criteria andA12NotEqualTo(String value) {
            addCriterion("A12 <>", value, "a12");
            return (Criteria) this;
        }

        public Criteria andA12GreaterThan(String value) {
            addCriterion("A12 >", value, "a12");
            return (Criteria) this;
        }

        public Criteria andA12GreaterThanOrEqualTo(String value) {
            addCriterion("A12 >=", value, "a12");
            return (Criteria) this;
        }

        public Criteria andA12LessThan(String value) {
            addCriterion("A12 <", value, "a12");
            return (Criteria) this;
        }

        public Criteria andA12LessThanOrEqualTo(String value) {
            addCriterion("A12 <=", value, "a12");
            return (Criteria) this;
        }

        public Criteria andA12Like(String value) {
            addCriterion("A12 like", value, "a12");
            return (Criteria) this;
        }

        public Criteria andA12NotLike(String value) {
            addCriterion("A12 not like", value, "a12");
            return (Criteria) this;
        }

        public Criteria andA12In(List<String> values) {
            addCriterion("A12 in", values, "a12");
            return (Criteria) this;
        }

        public Criteria andA12NotIn(List<String> values) {
            addCriterion("A12 not in", values, "a12");
            return (Criteria) this;
        }

        public Criteria andA12Between(String value1, String value2) {
            addCriterion("A12 between", value1, value2, "a12");
            return (Criteria) this;
        }

        public Criteria andA12NotBetween(String value1, String value2) {
            addCriterion("A12 not between", value1, value2, "a12");
            return (Criteria) this;
        }

        public Criteria andA18IsNull() {
            addCriterion("A18 is null");
            return (Criteria) this;
        }

        public Criteria andA18IsNotNull() {
            addCriterion("A18 is not null");
            return (Criteria) this;
        }

        public Criteria andA18EqualTo(String value) {
            addCriterion("A18 =", value, "a18");
            return (Criteria) this;
        }

        public Criteria andA18NotEqualTo(String value) {
            addCriterion("A18 <>", value, "a18");
            return (Criteria) this;
        }

        public Criteria andA18GreaterThan(String value) {
            addCriterion("A18 >", value, "a18");
            return (Criteria) this;
        }

        public Criteria andA18GreaterThanOrEqualTo(String value) {
            addCriterion("A18 >=", value, "a18");
            return (Criteria) this;
        }

        public Criteria andA18LessThan(String value) {
            addCriterion("A18 <", value, "a18");
            return (Criteria) this;
        }

        public Criteria andA18LessThanOrEqualTo(String value) {
            addCriterion("A18 <=", value, "a18");
            return (Criteria) this;
        }

        public Criteria andA18Like(String value) {
            addCriterion("A18 like", value, "a18");
            return (Criteria) this;
        }

        public Criteria andA18NotLike(String value) {
            addCriterion("A18 not like", value, "a18");
            return (Criteria) this;
        }

        public Criteria andA18In(List<String> values) {
            addCriterion("A18 in", values, "a18");
            return (Criteria) this;
        }

        public Criteria andA18NotIn(List<String> values) {
            addCriterion("A18 not in", values, "a18");
            return (Criteria) this;
        }

        public Criteria andA18Between(String value1, String value2) {
            addCriterion("A18 between", value1, value2, "a18");
            return (Criteria) this;
        }

        public Criteria andA18NotBetween(String value1, String value2) {
            addCriterion("A18 not between", value1, value2, "a18");
            return (Criteria) this;
        }

        public Criteria andA22IsNull() {
            addCriterion("A22 is null");
            return (Criteria) this;
        }

        public Criteria andA22IsNotNull() {
            addCriterion("A22 is not null");
            return (Criteria) this;
        }

        public Criteria andA22EqualTo(String value) {
            addCriterion("A22 =", value, "a22");
            return (Criteria) this;
        }

        public Criteria andA22NotEqualTo(String value) {
            addCriterion("A22 <>", value, "a22");
            return (Criteria) this;
        }

        public Criteria andA22GreaterThan(String value) {
            addCriterion("A22 >", value, "a22");
            return (Criteria) this;
        }

        public Criteria andA22GreaterThanOrEqualTo(String value) {
            addCriterion("A22 >=", value, "a22");
            return (Criteria) this;
        }

        public Criteria andA22LessThan(String value) {
            addCriterion("A22 <", value, "a22");
            return (Criteria) this;
        }

        public Criteria andA22LessThanOrEqualTo(String value) {
            addCriterion("A22 <=", value, "a22");
            return (Criteria) this;
        }

        public Criteria andA22Like(String value) {
            addCriterion("A22 like", value, "a22");
            return (Criteria) this;
        }

        public Criteria andA22NotLike(String value) {
            addCriterion("A22 not like", value, "a22");
            return (Criteria) this;
        }

        public Criteria andA22In(List<String> values) {
            addCriterion("A22 in", values, "a22");
            return (Criteria) this;
        }

        public Criteria andA22NotIn(List<String> values) {
            addCriterion("A22 not in", values, "a22");
            return (Criteria) this;
        }

        public Criteria andA22Between(String value1, String value2) {
            addCriterion("A22 between", value1, value2, "a22");
            return (Criteria) this;
        }

        public Criteria andA22NotBetween(String value1, String value2) {
            addCriterion("A22 not between", value1, value2, "a22");
            return (Criteria) this;
        }

        public Criteria andA9IsNull() {
            addCriterion("A9 is null");
            return (Criteria) this;
        }

        public Criteria andA9IsNotNull() {
            addCriterion("A9 is not null");
            return (Criteria) this;
        }

        public Criteria andA9EqualTo(String value) {
            addCriterion("A9 =", value, "a9");
            return (Criteria) this;
        }

        public Criteria andA9NotEqualTo(String value) {
            addCriterion("A9 <>", value, "a9");
            return (Criteria) this;
        }

        public Criteria andA9GreaterThan(String value) {
            addCriterion("A9 >", value, "a9");
            return (Criteria) this;
        }

        public Criteria andA9GreaterThanOrEqualTo(String value) {
            addCriterion("A9 >=", value, "a9");
            return (Criteria) this;
        }

        public Criteria andA9LessThan(String value) {
            addCriterion("A9 <", value, "a9");
            return (Criteria) this;
        }

        public Criteria andA9LessThanOrEqualTo(String value) {
            addCriterion("A9 <=", value, "a9");
            return (Criteria) this;
        }

        public Criteria andA9Like(String value) {
            addCriterion("A9 like", value, "a9");
            return (Criteria) this;
        }

        public Criteria andA9NotLike(String value) {
            addCriterion("A9 not like", value, "a9");
            return (Criteria) this;
        }

        public Criteria andA9In(List<String> values) {
            addCriterion("A9 in", values, "a9");
            return (Criteria) this;
        }

        public Criteria andA9NotIn(List<String> values) {
            addCriterion("A9 not in", values, "a9");
            return (Criteria) this;
        }

        public Criteria andA9Between(String value1, String value2) {
            addCriterion("A9 between", value1, value2, "a9");
            return (Criteria) this;
        }

        public Criteria andA9NotBetween(String value1, String value2) {
            addCriterion("A9 not between", value1, value2, "a9");
            return (Criteria) this;
        }

        public Criteria andA10IsNull() {
            addCriterion("A10 is null");
            return (Criteria) this;
        }

        public Criteria andA10IsNotNull() {
            addCriterion("A10 is not null");
            return (Criteria) this;
        }

        public Criteria andA10EqualTo(String value) {
            addCriterion("A10 =", value, "a10");
            return (Criteria) this;
        }

        public Criteria andA10NotEqualTo(String value) {
            addCriterion("A10 <>", value, "a10");
            return (Criteria) this;
        }

        public Criteria andA10GreaterThan(String value) {
            addCriterion("A10 >", value, "a10");
            return (Criteria) this;
        }

        public Criteria andA10GreaterThanOrEqualTo(String value) {
            addCriterion("A10 >=", value, "a10");
            return (Criteria) this;
        }

        public Criteria andA10LessThan(String value) {
            addCriterion("A10 <", value, "a10");
            return (Criteria) this;
        }

        public Criteria andA10LessThanOrEqualTo(String value) {
            addCriterion("A10 <=", value, "a10");
            return (Criteria) this;
        }

        public Criteria andA10Like(String value) {
            addCriterion("A10 like", value, "a10");
            return (Criteria) this;
        }

        public Criteria andA10NotLike(String value) {
            addCriterion("A10 not like", value, "a10");
            return (Criteria) this;
        }

        public Criteria andA10In(List<String> values) {
            addCriterion("A10 in", values, "a10");
            return (Criteria) this;
        }

        public Criteria andA10NotIn(List<String> values) {
            addCriterion("A10 not in", values, "a10");
            return (Criteria) this;
        }

        public Criteria andA10Between(String value1, String value2) {
            addCriterion("A10 between", value1, value2, "a10");
            return (Criteria) this;
        }

        public Criteria andA10NotBetween(String value1, String value2) {
            addCriterion("A10 not between", value1, value2, "a10");
            return (Criteria) this;
        }

        public Criteria andA17IsNull() {
            addCriterion("A17 is null");
            return (Criteria) this;
        }

        public Criteria andA17IsNotNull() {
            addCriterion("A17 is not null");
            return (Criteria) this;
        }

        public Criteria andA17EqualTo(String value) {
            addCriterion("A17 =", value, "a17");
            return (Criteria) this;
        }

        public Criteria andA17NotEqualTo(String value) {
            addCriterion("A17 <>", value, "a17");
            return (Criteria) this;
        }

        public Criteria andA17GreaterThan(String value) {
            addCriterion("A17 >", value, "a17");
            return (Criteria) this;
        }

        public Criteria andA17GreaterThanOrEqualTo(String value) {
            addCriterion("A17 >=", value, "a17");
            return (Criteria) this;
        }

        public Criteria andA17LessThan(String value) {
            addCriterion("A17 <", value, "a17");
            return (Criteria) this;
        }

        public Criteria andA17LessThanOrEqualTo(String value) {
            addCriterion("A17 <=", value, "a17");
            return (Criteria) this;
        }

        public Criteria andA17Like(String value) {
            addCriterion("A17 like", value, "a17");
            return (Criteria) this;
        }

        public Criteria andA17NotLike(String value) {
            addCriterion("A17 not like", value, "a17");
            return (Criteria) this;
        }

        public Criteria andA17In(List<String> values) {
            addCriterion("A17 in", values, "a17");
            return (Criteria) this;
        }

        public Criteria andA17NotIn(List<String> values) {
            addCriterion("A17 not in", values, "a17");
            return (Criteria) this;
        }

        public Criteria andA17Between(String value1, String value2) {
            addCriterion("A17 between", value1, value2, "a17");
            return (Criteria) this;
        }

        public Criteria andA17NotBetween(String value1, String value2) {
            addCriterion("A17 not between", value1, value2, "a17");
            return (Criteria) this;
        }

        public Criteria andA19IsNull() {
            addCriterion("A19 is null");
            return (Criteria) this;
        }

        public Criteria andA19IsNotNull() {
            addCriterion("A19 is not null");
            return (Criteria) this;
        }

        public Criteria andA19EqualTo(String value) {
            addCriterion("A19 =", value, "a19");
            return (Criteria) this;
        }

        public Criteria andA19NotEqualTo(String value) {
            addCriterion("A19 <>", value, "a19");
            return (Criteria) this;
        }

        public Criteria andA19GreaterThan(String value) {
            addCriterion("A19 >", value, "a19");
            return (Criteria) this;
        }

        public Criteria andA19GreaterThanOrEqualTo(String value) {
            addCriterion("A19 >=", value, "a19");
            return (Criteria) this;
        }

        public Criteria andA19LessThan(String value) {
            addCriterion("A19 <", value, "a19");
            return (Criteria) this;
        }

        public Criteria andA19LessThanOrEqualTo(String value) {
            addCriterion("A19 <=", value, "a19");
            return (Criteria) this;
        }

        public Criteria andA19Like(String value) {
            addCriterion("A19 like", value, "a19");
            return (Criteria) this;
        }

        public Criteria andA19NotLike(String value) {
            addCriterion("A19 not like", value, "a19");
            return (Criteria) this;
        }

        public Criteria andA19In(List<String> values) {
            addCriterion("A19 in", values, "a19");
            return (Criteria) this;
        }

        public Criteria andA19NotIn(List<String> values) {
            addCriterion("A19 not in", values, "a19");
            return (Criteria) this;
        }

        public Criteria andA19Between(String value1, String value2) {
            addCriterion("A19 between", value1, value2, "a19");
            return (Criteria) this;
        }

        public Criteria andA19NotBetween(String value1, String value2) {
            addCriterion("A19 not between", value1, value2, "a19");
            return (Criteria) this;
        }

        public Criteria andA11IsNull() {
            addCriterion("A11 is null");
            return (Criteria) this;
        }

        public Criteria andA11IsNotNull() {
            addCriterion("A11 is not null");
            return (Criteria) this;
        }

        public Criteria andA11EqualTo(String value) {
            addCriterion("A11 =", value, "a11");
            return (Criteria) this;
        }

        public Criteria andA11NotEqualTo(String value) {
            addCriterion("A11 <>", value, "a11");
            return (Criteria) this;
        }

        public Criteria andA11GreaterThan(String value) {
            addCriterion("A11 >", value, "a11");
            return (Criteria) this;
        }

        public Criteria andA11GreaterThanOrEqualTo(String value) {
            addCriterion("A11 >=", value, "a11");
            return (Criteria) this;
        }

        public Criteria andA11LessThan(String value) {
            addCriterion("A11 <", value, "a11");
            return (Criteria) this;
        }

        public Criteria andA11LessThanOrEqualTo(String value) {
            addCriterion("A11 <=", value, "a11");
            return (Criteria) this;
        }

        public Criteria andA11Like(String value) {
            addCriterion("A11 like", value, "a11");
            return (Criteria) this;
        }

        public Criteria andA11NotLike(String value) {
            addCriterion("A11 not like", value, "a11");
            return (Criteria) this;
        }

        public Criteria andA11In(List<String> values) {
            addCriterion("A11 in", values, "a11");
            return (Criteria) this;
        }

        public Criteria andA11NotIn(List<String> values) {
            addCriterion("A11 not in", values, "a11");
            return (Criteria) this;
        }

        public Criteria andA11Between(String value1, String value2) {
            addCriterion("A11 between", value1, value2, "a11");
            return (Criteria) this;
        }

        public Criteria andA11NotBetween(String value1, String value2) {
            addCriterion("A11 not between", value1, value2, "a11");
            return (Criteria) this;
        }

        public Criteria andTotalfeeIsNull() {
            addCriterion("TOTALFEE is null");
            return (Criteria) this;
        }

        public Criteria andTotalfeeIsNotNull() {
            addCriterion("TOTALFEE is not null");
            return (Criteria) this;
        }

        public Criteria andTotalfeeEqualTo(String value) {
            addCriterion("TOTALFEE =", value, "totalfee");
            return (Criteria) this;
        }

        public Criteria andTotalfeeNotEqualTo(String value) {
            addCriterion("TOTALFEE <>", value, "totalfee");
            return (Criteria) this;
        }

        public Criteria andTotalfeeGreaterThan(String value) {
            addCriterion("TOTALFEE >", value, "totalfee");
            return (Criteria) this;
        }

        public Criteria andTotalfeeGreaterThanOrEqualTo(String value) {
            addCriterion("TOTALFEE >=", value, "totalfee");
            return (Criteria) this;
        }

        public Criteria andTotalfeeLessThan(String value) {
            addCriterion("TOTALFEE <", value, "totalfee");
            return (Criteria) this;
        }

        public Criteria andTotalfeeLessThanOrEqualTo(String value) {
            addCriterion("TOTALFEE <=", value, "totalfee");
            return (Criteria) this;
        }

        public Criteria andTotalfeeLike(String value) {
            addCriterion("TOTALFEE like", value, "totalfee");
            return (Criteria) this;
        }

        public Criteria andTotalfeeNotLike(String value) {
            addCriterion("TOTALFEE not like", value, "totalfee");
            return (Criteria) this;
        }

        public Criteria andTotalfeeIn(List<String> values) {
            addCriterion("TOTALFEE in", values, "totalfee");
            return (Criteria) this;
        }

        public Criteria andTotalfeeNotIn(List<String> values) {
            addCriterion("TOTALFEE not in", values, "totalfee");
            return (Criteria) this;
        }

        public Criteria andTotalfeeBetween(String value1, String value2) {
            addCriterion("TOTALFEE between", value1, value2, "totalfee");
            return (Criteria) this;
        }

        public Criteria andTotalfeeNotBetween(String value1, String value2) {
            addCriterion("TOTALFEE not between", value1, value2, "totalfee");
            return (Criteria) this;
        }

        public Criteria andUndueinteamtIsNull() {
            addCriterion("UNDUEINTEAMT is null");
            return (Criteria) this;
        }

        public Criteria andUndueinteamtIsNotNull() {
            addCriterion("UNDUEINTEAMT is not null");
            return (Criteria) this;
        }

        public Criteria andUndueinteamtEqualTo(String value) {
            addCriterion("UNDUEINTEAMT =", value, "undueinteamt");
            return (Criteria) this;
        }

        public Criteria andUndueinteamtNotEqualTo(String value) {
            addCriterion("UNDUEINTEAMT <>", value, "undueinteamt");
            return (Criteria) this;
        }

        public Criteria andUndueinteamtGreaterThan(String value) {
            addCriterion("UNDUEINTEAMT >", value, "undueinteamt");
            return (Criteria) this;
        }

        public Criteria andUndueinteamtGreaterThanOrEqualTo(String value) {
            addCriterion("UNDUEINTEAMT >=", value, "undueinteamt");
            return (Criteria) this;
        }

        public Criteria andUndueinteamtLessThan(String value) {
            addCriterion("UNDUEINTEAMT <", value, "undueinteamt");
            return (Criteria) this;
        }

        public Criteria andUndueinteamtLessThanOrEqualTo(String value) {
            addCriterion("UNDUEINTEAMT <=", value, "undueinteamt");
            return (Criteria) this;
        }

        public Criteria andUndueinteamtLike(String value) {
            addCriterion("UNDUEINTEAMT like", value, "undueinteamt");
            return (Criteria) this;
        }

        public Criteria andUndueinteamtNotLike(String value) {
            addCriterion("UNDUEINTEAMT not like", value, "undueinteamt");
            return (Criteria) this;
        }

        public Criteria andUndueinteamtIn(List<String> values) {
            addCriterion("UNDUEINTEAMT in", values, "undueinteamt");
            return (Criteria) this;
        }

        public Criteria andUndueinteamtNotIn(List<String> values) {
            addCriterion("UNDUEINTEAMT not in", values, "undueinteamt");
            return (Criteria) this;
        }

        public Criteria andUndueinteamtBetween(String value1, String value2) {
            addCriterion("UNDUEINTEAMT between", value1, value2, "undueinteamt");
            return (Criteria) this;
        }

        public Criteria andUndueinteamtNotBetween(String value1, String value2) {
            addCriterion("UNDUEINTEAMT not between", value1, value2, "undueinteamt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}