package com.billionsfinance.bas.entity.voucher.model;

public class CwVoucherFactResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.ACCOUNTING_DATE
     *
     * @mbggenerated
     */
    private String accountingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.DUEDATE
     *
     * @mbggenerated
     */
    private String duedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.CUSTOMER_DIR
     *
     * @mbggenerated
     */
    private String customerDir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.BUSINESSMODEL
     *
     * @mbggenerated
     */
    private String businessmodel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.SUBPRODUCTTYPE
     *
     * @mbggenerated
     */
    private String subproducttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.PROVINCE
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.CITY
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.CITYCODE
     *
     * @mbggenerated
     */
    private String citycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.CANCELTYPE
     *
     * @mbggenerated
     */
    private String canceltype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.PAYTYPE
     *
     * @mbggenerated
     */
    private String paytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.CLASSFY
     *
     * @mbggenerated
     */
    private String classfy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.DELIVERYDATE
     *
     * @mbggenerated
     */
    private String deliverydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.DCDATE
     *
     * @mbggenerated
     */
    private String dcdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.SHDATE
     *
     * @mbggenerated
     */
    private String shdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.LPDATE
     *
     * @mbggenerated
     */
    private String lpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.DEBOURS
     *
     * @mbggenerated
     */
    private String debours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.ASSETBELONG
     *
     * @mbggenerated
     */
    private String assetbelong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.GUARANTEEPARTY
     *
     * @mbggenerated
     */
    private String guaranteeparty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.SPONSOR
     *
     * @mbggenerated
     */
    private String sponsor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.SPONSORTYPE
     *
     * @mbggenerated
     */
    private String sponsortype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.IS_INSTALMENTS_END
     *
     * @mbggenerated
     */
    private String isInstalmentsEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.BXHXDATE
     *
     * @mbggenerated
     */
    private String bxhxdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.ACTUALPAYDATE
     *
     * @mbggenerated
     */
    private String actualpaydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.PAYPRINCIPALAMT
     *
     * @mbggenerated
     */
    private String payprincipalamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.PAYINTEAMT
     *
     * @mbggenerated
     */
    private String payinteamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A2
     *
     * @mbggenerated
     */
    private String a2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A7
     *
     * @mbggenerated
     */
    private String a7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A12
     *
     * @mbggenerated
     */
    private String a12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A18
     *
     * @mbggenerated
     */
    private String a18;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A22
     *
     * @mbggenerated
     */
    private String a22;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A9
     *
     * @mbggenerated
     */
    private String a9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A10
     *
     * @mbggenerated
     */
    private String a10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A17
     *
     * @mbggenerated
     */
    private String a17;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A19
     *
     * @mbggenerated
     */
    private String a19;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A11
     *
     * @mbggenerated
     */
    private String a11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.TOTALFEE
     *
     * @mbggenerated
     */
    private String totalfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.UNDUEINTEAMT
     *
     * @mbggenerated
     */
    private String undueinteamt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.ACCOUNTING_DATE
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.ACCOUNTING_DATE
     *
     * @mbggenerated
     */
    public String getAccountingDate() {
        return accountingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.ACCOUNTING_DATE
     *
     * @param accountingDate the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.ACCOUNTING_DATE
     *
     * @mbggenerated
     */
    public void setAccountingDate(String accountingDate) {
        this.accountingDate = accountingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.DUEDATE
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.DUEDATE
     *
     * @mbggenerated
     */
    public String getDuedate() {
        return duedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.DUEDATE
     *
     * @param duedate the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.DUEDATE
     *
     * @mbggenerated
     */
    public void setDuedate(String duedate) {
        this.duedate = duedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.CUSTOMER_DIR
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.CUSTOMER_DIR
     *
     * @mbggenerated
     */
    public String getCustomerDir() {
        return customerDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.CUSTOMER_DIR
     *
     * @param customerDir the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.CUSTOMER_DIR
     *
     * @mbggenerated
     */
    public void setCustomerDir(String customerDir) {
        this.customerDir = customerDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.BUSINESSMODEL
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.BUSINESSMODEL
     *
     * @mbggenerated
     */
    public String getBusinessmodel() {
        return businessmodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.BUSINESSMODEL
     *
     * @param businessmodel the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.BUSINESSMODEL
     *
     * @mbggenerated
     */
    public void setBusinessmodel(String businessmodel) {
        this.businessmodel = businessmodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.SUBPRODUCTTYPE
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.SUBPRODUCTTYPE
     *
     * @mbggenerated
     */
    public String getSubproducttype() {
        return subproducttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.SUBPRODUCTTYPE
     *
     * @param subproducttype the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.SUBPRODUCTTYPE
     *
     * @mbggenerated
     */
    public void setSubproducttype(String subproducttype) {
        this.subproducttype = subproducttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.PROVINCE
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.PROVINCE
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.PROVINCE
     *
     * @param province the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.PROVINCE
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.CITY
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.CITY
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.CITY
     *
     * @param city the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.CITY
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.CITYCODE
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.CITYCODE
     *
     * @mbggenerated
     */
    public String getCitycode() {
        return citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.CITYCODE
     *
     * @param citycode the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.CITYCODE
     *
     * @mbggenerated
     */
    public void setCitycode(String citycode) {
        this.citycode = citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.CANCELTYPE
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.CANCELTYPE
     *
     * @mbggenerated
     */
    public String getCanceltype() {
        return canceltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.CANCELTYPE
     *
     * @param canceltype the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.CANCELTYPE
     *
     * @mbggenerated
     */
    public void setCanceltype(String canceltype) {
        this.canceltype = canceltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.PAYTYPE
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.PAYTYPE
     *
     * @mbggenerated
     */
    public String getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.PAYTYPE
     *
     * @param paytype the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.PAYTYPE
     *
     * @mbggenerated
     */
    public void setPaytype(String paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.CLASSFY
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.CLASSFY
     *
     * @mbggenerated
     */
    public String getClassfy() {
        return classfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.CLASSFY
     *
     * @param classfy the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.CLASSFY
     *
     * @mbggenerated
     */
    public void setClassfy(String classfy) {
        this.classfy = classfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.DELIVERYDATE
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.DELIVERYDATE
     *
     * @mbggenerated
     */
    public String getDeliverydate() {
        return deliverydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.DELIVERYDATE
     *
     * @param deliverydate the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.DELIVERYDATE
     *
     * @mbggenerated
     */
    public void setDeliverydate(String deliverydate) {
        this.deliverydate = deliverydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.DCDATE
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.DCDATE
     *
     * @mbggenerated
     */
    public String getDcdate() {
        return dcdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.DCDATE
     *
     * @param dcdate the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.DCDATE
     *
     * @mbggenerated
     */
    public void setDcdate(String dcdate) {
        this.dcdate = dcdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.SHDATE
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.SHDATE
     *
     * @mbggenerated
     */
    public String getShdate() {
        return shdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.SHDATE
     *
     * @param shdate the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.SHDATE
     *
     * @mbggenerated
     */
    public void setShdate(String shdate) {
        this.shdate = shdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.LPDATE
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.LPDATE
     *
     * @mbggenerated
     */
    public String getLpdate() {
        return lpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.LPDATE
     *
     * @param lpdate the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.LPDATE
     *
     * @mbggenerated
     */
    public void setLpdate(String lpdate) {
        this.lpdate = lpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.DEBOURS
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.DEBOURS
     *
     * @mbggenerated
     */
    public String getDebours() {
        return debours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.DEBOURS
     *
     * @param debours the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.DEBOURS
     *
     * @mbggenerated
     */
    public void setDebours(String debours) {
        this.debours = debours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.ASSETBELONG
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.ASSETBELONG
     *
     * @mbggenerated
     */
    public String getAssetbelong() {
        return assetbelong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.ASSETBELONG
     *
     * @param assetbelong the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.ASSETBELONG
     *
     * @mbggenerated
     */
    public void setAssetbelong(String assetbelong) {
        this.assetbelong = assetbelong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.GUARANTEEPARTY
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.GUARANTEEPARTY
     *
     * @mbggenerated
     */
    public String getGuaranteeparty() {
        return guaranteeparty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.GUARANTEEPARTY
     *
     * @param guaranteeparty the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.GUARANTEEPARTY
     *
     * @mbggenerated
     */
    public void setGuaranteeparty(String guaranteeparty) {
        this.guaranteeparty = guaranteeparty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.SPONSOR
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.SPONSOR
     *
     * @mbggenerated
     */
    public String getSponsor() {
        return sponsor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.SPONSOR
     *
     * @param sponsor the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.SPONSOR
     *
     * @mbggenerated
     */
    public void setSponsor(String sponsor) {
        this.sponsor = sponsor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.SPONSORTYPE
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.SPONSORTYPE
     *
     * @mbggenerated
     */
    public String getSponsortype() {
        return sponsortype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.SPONSORTYPE
     *
     * @param sponsortype the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.SPONSORTYPE
     *
     * @mbggenerated
     */
    public void setSponsortype(String sponsortype) {
        this.sponsortype = sponsortype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.IS_INSTALMENTS_END
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.IS_INSTALMENTS_END
     *
     * @mbggenerated
     */
    public String getIsInstalmentsEnd() {
        return isInstalmentsEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.IS_INSTALMENTS_END
     *
     * @param isInstalmentsEnd the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.IS_INSTALMENTS_END
     *
     * @mbggenerated
     */
    public void setIsInstalmentsEnd(String isInstalmentsEnd) {
        this.isInstalmentsEnd = isInstalmentsEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.BXHXDATE
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.BXHXDATE
     *
     * @mbggenerated
     */
    public String getBxhxdate() {
        return bxhxdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.BXHXDATE
     *
     * @param bxhxdate the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.BXHXDATE
     *
     * @mbggenerated
     */
    public void setBxhxdate(String bxhxdate) {
        this.bxhxdate = bxhxdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.ACTUALPAYDATE
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.ACTUALPAYDATE
     *
     * @mbggenerated
     */
    public String getActualpaydate() {
        return actualpaydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.ACTUALPAYDATE
     *
     * @param actualpaydate the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.ACTUALPAYDATE
     *
     * @mbggenerated
     */
    public void setActualpaydate(String actualpaydate) {
        this.actualpaydate = actualpaydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.PAYPRINCIPALAMT
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.PAYPRINCIPALAMT
     *
     * @mbggenerated
     */
    public String getPayprincipalamt() {
        return payprincipalamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.PAYPRINCIPALAMT
     *
     * @param payprincipalamt the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.PAYPRINCIPALAMT
     *
     * @mbggenerated
     */
    public void setPayprincipalamt(String payprincipalamt) {
        this.payprincipalamt = payprincipalamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.PAYINTEAMT
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.PAYINTEAMT
     *
     * @mbggenerated
     */
    public String getPayinteamt() {
        return payinteamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.PAYINTEAMT
     *
     * @param payinteamt the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.PAYINTEAMT
     *
     * @mbggenerated
     */
    public void setPayinteamt(String payinteamt) {
        this.payinteamt = payinteamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A2
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A2
     *
     * @mbggenerated
     */
    public String getA2() {
        return a2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A2
     *
     * @param a2 the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A2
     *
     * @mbggenerated
     */
    public void setA2(String a2) {
        this.a2 = a2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A7
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A7
     *
     * @mbggenerated
     */
    public String getA7() {
        return a7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A7
     *
     * @param a7 the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A7
     *
     * @mbggenerated
     */
    public void setA7(String a7) {
        this.a7 = a7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A12
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A12
     *
     * @mbggenerated
     */
    public String getA12() {
        return a12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A12
     *
     * @param a12 the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A12
     *
     * @mbggenerated
     */
    public void setA12(String a12) {
        this.a12 = a12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A18
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A18
     *
     * @mbggenerated
     */
    public String getA18() {
        return a18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A18
     *
     * @param a18 the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A18
     *
     * @mbggenerated
     */
    public void setA18(String a18) {
        this.a18 = a18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A22
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A22
     *
     * @mbggenerated
     */
    public String getA22() {
        return a22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A22
     *
     * @param a22 the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A22
     *
     * @mbggenerated
     */
    public void setA22(String a22) {
        this.a22 = a22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A9
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A9
     *
     * @mbggenerated
     */
    public String getA9() {
        return a9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A9
     *
     * @param a9 the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A9
     *
     * @mbggenerated
     */
    public void setA9(String a9) {
        this.a9 = a9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A10
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A10
     *
     * @mbggenerated
     */
    public String getA10() {
        return a10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A10
     *
     * @param a10 the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A10
     *
     * @mbggenerated
     */
    public void setA10(String a10) {
        this.a10 = a10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A17
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A17
     *
     * @mbggenerated
     */
    public String getA17() {
        return a17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A17
     *
     * @param a17 the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A17
     *
     * @mbggenerated
     */
    public void setA17(String a17) {
        this.a17 = a17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A19
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A19
     *
     * @mbggenerated
     */
    public String getA19() {
        return a19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A19
     *
     * @param a19 the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A19
     *
     * @mbggenerated
     */
    public void setA19(String a19) {
        this.a19 = a19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A11
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A11
     *
     * @mbggenerated
     */
    public String getA11() {
        return a11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A11
     *
     * @param a11 the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.A11
     *
     * @mbggenerated
     */
    public void setA11(String a11) {
        this.a11 = a11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.TOTALFEE
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.TOTALFEE
     *
     * @mbggenerated
     */
    public String getTotalfee() {
        return totalfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.TOTALFEE
     *
     * @param totalfee the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.TOTALFEE
     *
     * @mbggenerated
     */
    public void setTotalfee(String totalfee) {
        this.totalfee = totalfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.UNDUEINTEAMT
     *
     * @return the value of SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.UNDUEINTEAMT
     *
     * @mbggenerated
     */
    public String getUndueinteamt() {
        return undueinteamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.UNDUEINTEAMT
     *
     * @param undueinteamt the value for SITBAS_XFD_TMK.CW_VOUCHER_FACT_RESULT.UNDUEINTEAMT
     *
     * @mbggenerated
     */
    public void setUndueinteamt(String undueinteamt) {
        this.undueinteamt = undueinteamt;
    }
}