package com.billionsfinance.bas.entity.voucher.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class CwVoucherModelInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO
	 * @mbggenerated
	 */
	public CwVoucherModelInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(BigDecimal value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(BigDecimal value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(BigDecimal value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(BigDecimal value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(BigDecimal value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<BigDecimal> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<BigDecimal> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andBusinessmodelIsNull() {
			addCriterion("BUSINESSMODEL is null");
			return (Criteria) this;
		}

		public Criteria andBusinessmodelIsNotNull() {
			addCriterion("BUSINESSMODEL is not null");
			return (Criteria) this;
		}

		public Criteria andBusinessmodelEqualTo(String value) {
			addCriterion("BUSINESSMODEL =", value, "businessmodel");
			return (Criteria) this;
		}

		public Criteria andBusinessmodelNotEqualTo(String value) {
			addCriterion("BUSINESSMODEL <>", value, "businessmodel");
			return (Criteria) this;
		}

		public Criteria andBusinessmodelGreaterThan(String value) {
			addCriterion("BUSINESSMODEL >", value, "businessmodel");
			return (Criteria) this;
		}

		public Criteria andBusinessmodelGreaterThanOrEqualTo(String value) {
			addCriterion("BUSINESSMODEL >=", value, "businessmodel");
			return (Criteria) this;
		}

		public Criteria andBusinessmodelLessThan(String value) {
			addCriterion("BUSINESSMODEL <", value, "businessmodel");
			return (Criteria) this;
		}

		public Criteria andBusinessmodelLessThanOrEqualTo(String value) {
			addCriterion("BUSINESSMODEL <=", value, "businessmodel");
			return (Criteria) this;
		}

		public Criteria andBusinessmodelLike(String value) {
			addCriterion("BUSINESSMODEL like", value, "businessmodel");
			return (Criteria) this;
		}

		public Criteria andBusinessmodelNotLike(String value) {
			addCriterion("BUSINESSMODEL not like", value, "businessmodel");
			return (Criteria) this;
		}

		public Criteria andBusinessmodelIn(List<String> values) {
			addCriterion("BUSINESSMODEL in", values, "businessmodel");
			return (Criteria) this;
		}

		public Criteria andBusinessmodelNotIn(List<String> values) {
			addCriterion("BUSINESSMODEL not in", values, "businessmodel");
			return (Criteria) this;
		}

		public Criteria andBusinessmodelBetween(String value1, String value2) {
			addCriterion("BUSINESSMODEL between", value1, value2,
					"businessmodel");
			return (Criteria) this;
		}

		public Criteria andBusinessmodelNotBetween(String value1, String value2) {
			addCriterion("BUSINESSMODEL not between", value1, value2,
					"businessmodel");
			return (Criteria) this;
		}

		public Criteria andCityIsNull() {
			addCriterion("CITY is null");
			return (Criteria) this;
		}

		public Criteria andCityIsNotNull() {
			addCriterion("CITY is not null");
			return (Criteria) this;
		}

		public Criteria andCityEqualTo(String value) {
			addCriterion("CITY =", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotEqualTo(String value) {
			addCriterion("CITY <>", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityGreaterThan(String value) {
			addCriterion("CITY >", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityGreaterThanOrEqualTo(String value) {
			addCriterion("CITY >=", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLessThan(String value) {
			addCriterion("CITY <", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLessThanOrEqualTo(String value) {
			addCriterion("CITY <=", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLike(String value) {
			addCriterion("CITY like", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotLike(String value) {
			addCriterion("CITY not like", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityIn(List<String> values) {
			addCriterion("CITY in", values, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotIn(List<String> values) {
			addCriterion("CITY not in", values, "city");
			return (Criteria) this;
		}

		public Criteria andCityBetween(String value1, String value2) {
			addCriterion("CITY between", value1, value2, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotBetween(String value1, String value2) {
			addCriterion("CITY not between", value1, value2, "city");
			return (Criteria) this;
		}

		public Criteria andCanceltypeIsNull() {
			addCriterion("CANCELTYPE is null");
			return (Criteria) this;
		}

		public Criteria andCanceltypeIsNotNull() {
			addCriterion("CANCELTYPE is not null");
			return (Criteria) this;
		}

		public Criteria andCanceltypeEqualTo(String value) {
			addCriterion("CANCELTYPE =", value, "canceltype");
			return (Criteria) this;
		}

		public Criteria andCanceltypeNotEqualTo(String value) {
			addCriterion("CANCELTYPE <>", value, "canceltype");
			return (Criteria) this;
		}

		public Criteria andCanceltypeGreaterThan(String value) {
			addCriterion("CANCELTYPE >", value, "canceltype");
			return (Criteria) this;
		}

		public Criteria andCanceltypeGreaterThanOrEqualTo(String value) {
			addCriterion("CANCELTYPE >=", value, "canceltype");
			return (Criteria) this;
		}

		public Criteria andCanceltypeLessThan(String value) {
			addCriterion("CANCELTYPE <", value, "canceltype");
			return (Criteria) this;
		}

		public Criteria andCanceltypeLessThanOrEqualTo(String value) {
			addCriterion("CANCELTYPE <=", value, "canceltype");
			return (Criteria) this;
		}

		public Criteria andCanceltypeLike(String value) {
			addCriterion("CANCELTYPE like", value, "canceltype");
			return (Criteria) this;
		}

		public Criteria andCanceltypeNotLike(String value) {
			addCriterion("CANCELTYPE not like", value, "canceltype");
			return (Criteria) this;
		}

		public Criteria andCanceltypeIn(List<String> values) {
			addCriterion("CANCELTYPE in", values, "canceltype");
			return (Criteria) this;
		}

		public Criteria andCanceltypeNotIn(List<String> values) {
			addCriterion("CANCELTYPE not in", values, "canceltype");
			return (Criteria) this;
		}

		public Criteria andCanceltypeBetween(String value1, String value2) {
			addCriterion("CANCELTYPE between", value1, value2, "canceltype");
			return (Criteria) this;
		}

		public Criteria andCanceltypeNotBetween(String value1, String value2) {
			addCriterion("CANCELTYPE not between", value1, value2, "canceltype");
			return (Criteria) this;
		}

		public Criteria andAssetbelongIsNull() {
			addCriterion("ASSETBELONG is null");
			return (Criteria) this;
		}

		public Criteria andAssetbelongIsNotNull() {
			addCriterion("ASSETBELONG is not null");
			return (Criteria) this;
		}

		public Criteria andAssetbelongEqualTo(String value) {
			addCriterion("ASSETBELONG =", value, "assetbelong");
			return (Criteria) this;
		}

		public Criteria andAssetbelongNotEqualTo(String value) {
			addCriterion("ASSETBELONG <>", value, "assetbelong");
			return (Criteria) this;
		}

		public Criteria andAssetbelongGreaterThan(String value) {
			addCriterion("ASSETBELONG >", value, "assetbelong");
			return (Criteria) this;
		}

		public Criteria andAssetbelongGreaterThanOrEqualTo(String value) {
			addCriterion("ASSETBELONG >=", value, "assetbelong");
			return (Criteria) this;
		}

		public Criteria andAssetbelongLessThan(String value) {
			addCriterion("ASSETBELONG <", value, "assetbelong");
			return (Criteria) this;
		}

		public Criteria andAssetbelongLessThanOrEqualTo(String value) {
			addCriterion("ASSETBELONG <=", value, "assetbelong");
			return (Criteria) this;
		}

		public Criteria andAssetbelongLike(String value) {
			addCriterion("ASSETBELONG like", value, "assetbelong");
			return (Criteria) this;
		}

		public Criteria andAssetbelongNotLike(String value) {
			addCriterion("ASSETBELONG not like", value, "assetbelong");
			return (Criteria) this;
		}

		public Criteria andAssetbelongIn(List<String> values) {
			addCriterion("ASSETBELONG in", values, "assetbelong");
			return (Criteria) this;
		}

		public Criteria andAssetbelongNotIn(List<String> values) {
			addCriterion("ASSETBELONG not in", values, "assetbelong");
			return (Criteria) this;
		}

		public Criteria andAssetbelongBetween(String value1, String value2) {
			addCriterion("ASSETBELONG between", value1, value2, "assetbelong");
			return (Criteria) this;
		}

		public Criteria andAssetbelongNotBetween(String value1, String value2) {
			addCriterion("ASSETBELONG not between", value1, value2,
					"assetbelong");
			return (Criteria) this;
		}

		public Criteria andGuaranteepartyIsNull() {
			addCriterion("GUARANTEEPARTY is null");
			return (Criteria) this;
		}

		public Criteria andGuaranteepartyIsNotNull() {
			addCriterion("GUARANTEEPARTY is not null");
			return (Criteria) this;
		}

		public Criteria andGuaranteepartyEqualTo(String value) {
			addCriterion("GUARANTEEPARTY =", value, "guaranteeparty");
			return (Criteria) this;
		}

		public Criteria andGuaranteepartyNotEqualTo(String value) {
			addCriterion("GUARANTEEPARTY <>", value, "guaranteeparty");
			return (Criteria) this;
		}

		public Criteria andGuaranteepartyGreaterThan(String value) {
			addCriterion("GUARANTEEPARTY >", value, "guaranteeparty");
			return (Criteria) this;
		}

		public Criteria andGuaranteepartyGreaterThanOrEqualTo(String value) {
			addCriterion("GUARANTEEPARTY >=", value, "guaranteeparty");
			return (Criteria) this;
		}

		public Criteria andGuaranteepartyLessThan(String value) {
			addCriterion("GUARANTEEPARTY <", value, "guaranteeparty");
			return (Criteria) this;
		}

		public Criteria andGuaranteepartyLessThanOrEqualTo(String value) {
			addCriterion("GUARANTEEPARTY <=", value, "guaranteeparty");
			return (Criteria) this;
		}

		public Criteria andGuaranteepartyLike(String value) {
			addCriterion("GUARANTEEPARTY like", value, "guaranteeparty");
			return (Criteria) this;
		}

		public Criteria andGuaranteepartyNotLike(String value) {
			addCriterion("GUARANTEEPARTY not like", value, "guaranteeparty");
			return (Criteria) this;
		}

		public Criteria andGuaranteepartyIn(List<String> values) {
			addCriterion("GUARANTEEPARTY in", values, "guaranteeparty");
			return (Criteria) this;
		}

		public Criteria andGuaranteepartyNotIn(List<String> values) {
			addCriterion("GUARANTEEPARTY not in", values, "guaranteeparty");
			return (Criteria) this;
		}

		public Criteria andGuaranteepartyBetween(String value1, String value2) {
			addCriterion("GUARANTEEPARTY between", value1, value2,
					"guaranteeparty");
			return (Criteria) this;
		}

		public Criteria andGuaranteepartyNotBetween(String value1, String value2) {
			addCriterion("GUARANTEEPARTY not between", value1, value2,
					"guaranteeparty");
			return (Criteria) this;
		}

		public Criteria andRelationIsNull() {
			addCriterion("RELATION is null");
			return (Criteria) this;
		}

		public Criteria andRelationIsNotNull() {
			addCriterion("RELATION is not null");
			return (Criteria) this;
		}

		public Criteria andRelationEqualTo(String value) {
			addCriterion("RELATION =", value, "relation");
			return (Criteria) this;
		}

		public Criteria andRelationNotEqualTo(String value) {
			addCriterion("RELATION <>", value, "relation");
			return (Criteria) this;
		}

		public Criteria andRelationGreaterThan(String value) {
			addCriterion("RELATION >", value, "relation");
			return (Criteria) this;
		}

		public Criteria andRelationGreaterThanOrEqualTo(String value) {
			addCriterion("RELATION >=", value, "relation");
			return (Criteria) this;
		}

		public Criteria andRelationLessThan(String value) {
			addCriterion("RELATION <", value, "relation");
			return (Criteria) this;
		}

		public Criteria andRelationLessThanOrEqualTo(String value) {
			addCriterion("RELATION <=", value, "relation");
			return (Criteria) this;
		}

		public Criteria andRelationLike(String value) {
			addCriterion("RELATION like", value, "relation");
			return (Criteria) this;
		}

		public Criteria andRelationNotLike(String value) {
			addCriterion("RELATION not like", value, "relation");
			return (Criteria) this;
		}

		public Criteria andRelationIn(List<String> values) {
			addCriterion("RELATION in", values, "relation");
			return (Criteria) this;
		}

		public Criteria andRelationNotIn(List<String> values) {
			addCriterion("RELATION not in", values, "relation");
			return (Criteria) this;
		}

		public Criteria andRelationBetween(String value1, String value2) {
			addCriterion("RELATION between", value1, value2, "relation");
			return (Criteria) this;
		}

		public Criteria andRelationNotBetween(String value1, String value2) {
			addCriterion("RELATION not between", value1, value2, "relation");
			return (Criteria) this;
		}

		public Criteria andSponsorIsNull() {
			addCriterion("SPONSOR is null");
			return (Criteria) this;
		}

		public Criteria andSponsorIsNotNull() {
			addCriterion("SPONSOR is not null");
			return (Criteria) this;
		}

		public Criteria andSponsorEqualTo(String value) {
			addCriterion("SPONSOR =", value, "sponsor");
			return (Criteria) this;
		}

		public Criteria andSponsorNotEqualTo(String value) {
			addCriterion("SPONSOR <>", value, "sponsor");
			return (Criteria) this;
		}

		public Criteria andSponsorGreaterThan(String value) {
			addCriterion("SPONSOR >", value, "sponsor");
			return (Criteria) this;
		}

		public Criteria andSponsorGreaterThanOrEqualTo(String value) {
			addCriterion("SPONSOR >=", value, "sponsor");
			return (Criteria) this;
		}

		public Criteria andSponsorLessThan(String value) {
			addCriterion("SPONSOR <", value, "sponsor");
			return (Criteria) this;
		}

		public Criteria andSponsorLessThanOrEqualTo(String value) {
			addCriterion("SPONSOR <=", value, "sponsor");
			return (Criteria) this;
		}

		public Criteria andSponsorLike(String value) {
			addCriterion("SPONSOR like", value, "sponsor");
			return (Criteria) this;
		}

		public Criteria andSponsorNotLike(String value) {
			addCriterion("SPONSOR not like", value, "sponsor");
			return (Criteria) this;
		}

		public Criteria andSponsorIn(List<String> values) {
			addCriterion("SPONSOR in", values, "sponsor");
			return (Criteria) this;
		}

		public Criteria andSponsorNotIn(List<String> values) {
			addCriterion("SPONSOR not in", values, "sponsor");
			return (Criteria) this;
		}

		public Criteria andSponsorBetween(String value1, String value2) {
			addCriterion("SPONSOR between", value1, value2, "sponsor");
			return (Criteria) this;
		}

		public Criteria andSponsorNotBetween(String value1, String value2) {
			addCriterion("SPONSOR not between", value1, value2, "sponsor");
			return (Criteria) this;
		}

		public Criteria andSponsortypeIsNull() {
			addCriterion("SPONSORTYPE is null");
			return (Criteria) this;
		}

		public Criteria andSponsortypeIsNotNull() {
			addCriterion("SPONSORTYPE is not null");
			return (Criteria) this;
		}

		public Criteria andSponsortypeEqualTo(String value) {
			addCriterion("SPONSORTYPE =", value, "sponsortype");
			return (Criteria) this;
		}

		public Criteria andSponsortypeNotEqualTo(String value) {
			addCriterion("SPONSORTYPE <>", value, "sponsortype");
			return (Criteria) this;
		}

		public Criteria andSponsortypeGreaterThan(String value) {
			addCriterion("SPONSORTYPE >", value, "sponsortype");
			return (Criteria) this;
		}

		public Criteria andSponsortypeGreaterThanOrEqualTo(String value) {
			addCriterion("SPONSORTYPE >=", value, "sponsortype");
			return (Criteria) this;
		}

		public Criteria andSponsortypeLessThan(String value) {
			addCriterion("SPONSORTYPE <", value, "sponsortype");
			return (Criteria) this;
		}

		public Criteria andSponsortypeLessThanOrEqualTo(String value) {
			addCriterion("SPONSORTYPE <=", value, "sponsortype");
			return (Criteria) this;
		}

		public Criteria andSponsortypeLike(String value) {
			addCriterion("SPONSORTYPE like", value, "sponsortype");
			return (Criteria) this;
		}

		public Criteria andSponsortypeNotLike(String value) {
			addCriterion("SPONSORTYPE not like", value, "sponsortype");
			return (Criteria) this;
		}

		public Criteria andSponsortypeIn(List<String> values) {
			addCriterion("SPONSORTYPE in", values, "sponsortype");
			return (Criteria) this;
		}

		public Criteria andSponsortypeNotIn(List<String> values) {
			addCriterion("SPONSORTYPE not in", values, "sponsortype");
			return (Criteria) this;
		}

		public Criteria andSponsortypeBetween(String value1, String value2) {
			addCriterion("SPONSORTYPE between", value1, value2, "sponsortype");
			return (Criteria) this;
		}

		public Criteria andSponsortypeNotBetween(String value1, String value2) {
			addCriterion("SPONSORTYPE not between", value1, value2,
					"sponsortype");
			return (Criteria) this;
		}

		public Criteria andIsInstalmentsEndIsNull() {
			addCriterion("IS_INSTALMENTS_END is null");
			return (Criteria) this;
		}

		public Criteria andIsInstalmentsEndIsNotNull() {
			addCriterion("IS_INSTALMENTS_END is not null");
			return (Criteria) this;
		}

		public Criteria andIsInstalmentsEndEqualTo(String value) {
			addCriterion("IS_INSTALMENTS_END =", value, "isInstalmentsEnd");
			return (Criteria) this;
		}

		public Criteria andIsInstalmentsEndNotEqualTo(String value) {
			addCriterion("IS_INSTALMENTS_END <>", value, "isInstalmentsEnd");
			return (Criteria) this;
		}

		public Criteria andIsInstalmentsEndGreaterThan(String value) {
			addCriterion("IS_INSTALMENTS_END >", value, "isInstalmentsEnd");
			return (Criteria) this;
		}

		public Criteria andIsInstalmentsEndGreaterThanOrEqualTo(String value) {
			addCriterion("IS_INSTALMENTS_END >=", value, "isInstalmentsEnd");
			return (Criteria) this;
		}

		public Criteria andIsInstalmentsEndLessThan(String value) {
			addCriterion("IS_INSTALMENTS_END <", value, "isInstalmentsEnd");
			return (Criteria) this;
		}

		public Criteria andIsInstalmentsEndLessThanOrEqualTo(String value) {
			addCriterion("IS_INSTALMENTS_END <=", value, "isInstalmentsEnd");
			return (Criteria) this;
		}

		public Criteria andIsInstalmentsEndLike(String value) {
			addCriterion("IS_INSTALMENTS_END like", value, "isInstalmentsEnd");
			return (Criteria) this;
		}

		public Criteria andIsInstalmentsEndNotLike(String value) {
			addCriterion("IS_INSTALMENTS_END not like", value,
					"isInstalmentsEnd");
			return (Criteria) this;
		}

		public Criteria andIsInstalmentsEndIn(List<String> values) {
			addCriterion("IS_INSTALMENTS_END in", values, "isInstalmentsEnd");
			return (Criteria) this;
		}

		public Criteria andIsInstalmentsEndNotIn(List<String> values) {
			addCriterion("IS_INSTALMENTS_END not in", values,
					"isInstalmentsEnd");
			return (Criteria) this;
		}

		public Criteria andIsInstalmentsEndBetween(String value1, String value2) {
			addCriterion("IS_INSTALMENTS_END between", value1, value2,
					"isInstalmentsEnd");
			return (Criteria) this;
		}

		public Criteria andIsInstalmentsEndNotBetween(String value1,
				String value2) {
			addCriterion("IS_INSTALMENTS_END not between", value1, value2,
					"isInstalmentsEnd");
			return (Criteria) this;
		}

		public Criteria andBadDebtDateIsNull() {
			addCriterion("BAD_DEBT_DATE is null");
			return (Criteria) this;
		}

		public Criteria andBadDebtDateIsNotNull() {
			addCriterion("BAD_DEBT_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andBadDebtDateEqualTo(String value) {
			addCriterion("BAD_DEBT_DATE =", value, "badDebtDate");
			return (Criteria) this;
		}

		public Criteria andBadDebtDateNotEqualTo(String value) {
			addCriterion("BAD_DEBT_DATE <>", value, "badDebtDate");
			return (Criteria) this;
		}

		public Criteria andBadDebtDateGreaterThan(String value) {
			addCriterion("BAD_DEBT_DATE >", value, "badDebtDate");
			return (Criteria) this;
		}

		public Criteria andBadDebtDateGreaterThanOrEqualTo(String value) {
			addCriterion("BAD_DEBT_DATE >=", value, "badDebtDate");
			return (Criteria) this;
		}

		public Criteria andBadDebtDateLessThan(String value) {
			addCriterion("BAD_DEBT_DATE <", value, "badDebtDate");
			return (Criteria) this;
		}

		public Criteria andBadDebtDateLessThanOrEqualTo(String value) {
			addCriterion("BAD_DEBT_DATE <=", value, "badDebtDate");
			return (Criteria) this;
		}

		public Criteria andBadDebtDateLike(String value) {
			addCriterion("BAD_DEBT_DATE like", value, "badDebtDate");
			return (Criteria) this;
		}

		public Criteria andBadDebtDateNotLike(String value) {
			addCriterion("BAD_DEBT_DATE not like", value, "badDebtDate");
			return (Criteria) this;
		}

		public Criteria andBadDebtDateIn(List<String> values) {
			addCriterion("BAD_DEBT_DATE in", values, "badDebtDate");
			return (Criteria) this;
		}

		public Criteria andBadDebtDateNotIn(List<String> values) {
			addCriterion("BAD_DEBT_DATE not in", values, "badDebtDate");
			return (Criteria) this;
		}

		public Criteria andBadDebtDateBetween(String value1, String value2) {
			addCriterion("BAD_DEBT_DATE between", value1, value2, "badDebtDate");
			return (Criteria) this;
		}

		public Criteria andBadDebtDateNotBetween(String value1, String value2) {
			addCriterion("BAD_DEBT_DATE not between", value1, value2,
					"badDebtDate");
			return (Criteria) this;
		}

		public Criteria andCalculatedAmountFieldIsNull() {
			addCriterion("CALCULATED_AMOUNT_FIELD is null");
			return (Criteria) this;
		}

		public Criteria andCalculatedAmountFieldIsNotNull() {
			addCriterion("CALCULATED_AMOUNT_FIELD is not null");
			return (Criteria) this;
		}

		public Criteria andCalculatedAmountFieldEqualTo(String value) {
			addCriterion("CALCULATED_AMOUNT_FIELD =", value,
					"calculatedAmountField");
			return (Criteria) this;
		}

		public Criteria andCalculatedAmountFieldNotEqualTo(String value) {
			addCriterion("CALCULATED_AMOUNT_FIELD <>", value,
					"calculatedAmountField");
			return (Criteria) this;
		}

		public Criteria andCalculatedAmountFieldGreaterThan(String value) {
			addCriterion("CALCULATED_AMOUNT_FIELD >", value,
					"calculatedAmountField");
			return (Criteria) this;
		}

		public Criteria andCalculatedAmountFieldGreaterThanOrEqualTo(
				String value) {
			addCriterion("CALCULATED_AMOUNT_FIELD >=", value,
					"calculatedAmountField");
			return (Criteria) this;
		}

		public Criteria andCalculatedAmountFieldLessThan(String value) {
			addCriterion("CALCULATED_AMOUNT_FIELD <", value,
					"calculatedAmountField");
			return (Criteria) this;
		}

		public Criteria andCalculatedAmountFieldLessThanOrEqualTo(String value) {
			addCriterion("CALCULATED_AMOUNT_FIELD <=", value,
					"calculatedAmountField");
			return (Criteria) this;
		}

		public Criteria andCalculatedAmountFieldLike(String value) {
			addCriterion("CALCULATED_AMOUNT_FIELD like", value,
					"calculatedAmountField");
			return (Criteria) this;
		}

		public Criteria andCalculatedAmountFieldNotLike(String value) {
			addCriterion("CALCULATED_AMOUNT_FIELD not like", value,
					"calculatedAmountField");
			return (Criteria) this;
		}

		public Criteria andCalculatedAmountFieldIn(List<String> values) {
			addCriterion("CALCULATED_AMOUNT_FIELD in", values,
					"calculatedAmountField");
			return (Criteria) this;
		}

		public Criteria andCalculatedAmountFieldNotIn(List<String> values) {
			addCriterion("CALCULATED_AMOUNT_FIELD not in", values,
					"calculatedAmountField");
			return (Criteria) this;
		}

		public Criteria andCalculatedAmountFieldBetween(String value1,
				String value2) {
			addCriterion("CALCULATED_AMOUNT_FIELD between", value1, value2,
					"calculatedAmountField");
			return (Criteria) this;
		}

		public Criteria andCalculatedAmountFieldNotBetween(String value1,
				String value2) {
			addCriterion("CALCULATED_AMOUNT_FIELD not between", value1, value2,
					"calculatedAmountField");
			return (Criteria) this;
		}

		public Criteria andAccountNumIsNull() {
			addCriterion("ACCOUNT_NUM is null");
			return (Criteria) this;
		}

		public Criteria andAccountNumIsNotNull() {
			addCriterion("ACCOUNT_NUM is not null");
			return (Criteria) this;
		}

		public Criteria andAccountNumEqualTo(String value) {
			addCriterion("ACCOUNT_NUM =", value, "accountNum");
			return (Criteria) this;
		}

		public Criteria andAccountNumNotEqualTo(String value) {
			addCriterion("ACCOUNT_NUM <>", value, "accountNum");
			return (Criteria) this;
		}

		public Criteria andAccountNumGreaterThan(String value) {
			addCriterion("ACCOUNT_NUM >", value, "accountNum");
			return (Criteria) this;
		}

		public Criteria andAccountNumGreaterThanOrEqualTo(String value) {
			addCriterion("ACCOUNT_NUM >=", value, "accountNum");
			return (Criteria) this;
		}

		public Criteria andAccountNumLessThan(String value) {
			addCriterion("ACCOUNT_NUM <", value, "accountNum");
			return (Criteria) this;
		}

		public Criteria andAccountNumLessThanOrEqualTo(String value) {
			addCriterion("ACCOUNT_NUM <=", value, "accountNum");
			return (Criteria) this;
		}

		public Criteria andAccountNumLike(String value) {
			addCriterion("ACCOUNT_NUM like", value, "accountNum");
			return (Criteria) this;
		}

		public Criteria andAccountNumNotLike(String value) {
			addCriterion("ACCOUNT_NUM not like", value, "accountNum");
			return (Criteria) this;
		}

		public Criteria andAccountNumIn(List<String> values) {
			addCriterion("ACCOUNT_NUM in", values, "accountNum");
			return (Criteria) this;
		}

		public Criteria andAccountNumNotIn(List<String> values) {
			addCriterion("ACCOUNT_NUM not in", values, "accountNum");
			return (Criteria) this;
		}

		public Criteria andAccountNumBetween(String value1, String value2) {
			addCriterion("ACCOUNT_NUM between", value1, value2, "accountNum");
			return (Criteria) this;
		}

		public Criteria andAccountNumNotBetween(String value1, String value2) {
			addCriterion("ACCOUNT_NUM not between", value1, value2,
					"accountNum");
			return (Criteria) this;
		}

		public Criteria andAccountDirIsNull() {
			addCriterion("ACCOUNT_DIR is null");
			return (Criteria) this;
		}

		public Criteria andAccountDirIsNotNull() {
			addCriterion("ACCOUNT_DIR is not null");
			return (Criteria) this;
		}

		public Criteria andAccountDirEqualTo(String value) {
			addCriterion("ACCOUNT_DIR =", value, "accountDir");
			return (Criteria) this;
		}

		public Criteria andAccountDirNotEqualTo(String value) {
			addCriterion("ACCOUNT_DIR <>", value, "accountDir");
			return (Criteria) this;
		}

		public Criteria andAccountDirGreaterThan(String value) {
			addCriterion("ACCOUNT_DIR >", value, "accountDir");
			return (Criteria) this;
		}

		public Criteria andAccountDirGreaterThanOrEqualTo(String value) {
			addCriterion("ACCOUNT_DIR >=", value, "accountDir");
			return (Criteria) this;
		}

		public Criteria andAccountDirLessThan(String value) {
			addCriterion("ACCOUNT_DIR <", value, "accountDir");
			return (Criteria) this;
		}

		public Criteria andAccountDirLessThanOrEqualTo(String value) {
			addCriterion("ACCOUNT_DIR <=", value, "accountDir");
			return (Criteria) this;
		}

		public Criteria andAccountDirLike(String value) {
			addCriterion("ACCOUNT_DIR like", value, "accountDir");
			return (Criteria) this;
		}

		public Criteria andAccountDirNotLike(String value) {
			addCriterion("ACCOUNT_DIR not like", value, "accountDir");
			return (Criteria) this;
		}

		public Criteria andAccountDirIn(List<String> values) {
			addCriterion("ACCOUNT_DIR in", values, "accountDir");
			return (Criteria) this;
		}

		public Criteria andAccountDirNotIn(List<String> values) {
			addCriterion("ACCOUNT_DIR not in", values, "accountDir");
			return (Criteria) this;
		}

		public Criteria andAccountDirBetween(String value1, String value2) {
			addCriterion("ACCOUNT_DIR between", value1, value2, "accountDir");
			return (Criteria) this;
		}

		public Criteria andAccountDirNotBetween(String value1, String value2) {
			addCriterion("ACCOUNT_DIR not between", value1, value2,
					"accountDir");
			return (Criteria) this;
		}

		public Criteria andSubjectNumIsNull() {
			addCriterion("SUBJECT_NUM is null");
			return (Criteria) this;
		}

		public Criteria andSubjectNumIsNotNull() {
			addCriterion("SUBJECT_NUM is not null");
			return (Criteria) this;
		}

		public Criteria andSubjectNumEqualTo(String value) {
			addCriterion("SUBJECT_NUM =", value, "subjectNum");
			return (Criteria) this;
		}

		public Criteria andSubjectNumNotEqualTo(String value) {
			addCriterion("SUBJECT_NUM <>", value, "subjectNum");
			return (Criteria) this;
		}

		public Criteria andSubjectNumGreaterThan(String value) {
			addCriterion("SUBJECT_NUM >", value, "subjectNum");
			return (Criteria) this;
		}

		public Criteria andSubjectNumGreaterThanOrEqualTo(String value) {
			addCriterion("SUBJECT_NUM >=", value, "subjectNum");
			return (Criteria) this;
		}

		public Criteria andSubjectNumLessThan(String value) {
			addCriterion("SUBJECT_NUM <", value, "subjectNum");
			return (Criteria) this;
		}

		public Criteria andSubjectNumLessThanOrEqualTo(String value) {
			addCriterion("SUBJECT_NUM <=", value, "subjectNum");
			return (Criteria) this;
		}

		public Criteria andSubjectNumLike(String value) {
			addCriterion("SUBJECT_NUM like", value, "subjectNum");
			return (Criteria) this;
		}

		public Criteria andSubjectNumNotLike(String value) {
			addCriterion("SUBJECT_NUM not like", value, "subjectNum");
			return (Criteria) this;
		}

		public Criteria andSubjectNumIn(List<String> values) {
			addCriterion("SUBJECT_NUM in", values, "subjectNum");
			return (Criteria) this;
		}

		public Criteria andSubjectNumNotIn(List<String> values) {
			addCriterion("SUBJECT_NUM not in", values, "subjectNum");
			return (Criteria) this;
		}

		public Criteria andSubjectNumBetween(String value1, String value2) {
			addCriterion("SUBJECT_NUM between", value1, value2, "subjectNum");
			return (Criteria) this;
		}

		public Criteria andSubjectNumNotBetween(String value1, String value2) {
			addCriterion("SUBJECT_NUM not between", value1, value2,
					"subjectNum");
			return (Criteria) this;
		}

		public Criteria andAccountingSubIsNull() {
			addCriterion("ACCOUNTING_SUB is null");
			return (Criteria) this;
		}

		public Criteria andAccountingSubIsNotNull() {
			addCriterion("ACCOUNTING_SUB is not null");
			return (Criteria) this;
		}

		public Criteria andAccountingSubEqualTo(String value) {
			addCriterion("ACCOUNTING_SUB =", value, "accountingSub");
			return (Criteria) this;
		}

		public Criteria andAccountingSubNotEqualTo(String value) {
			addCriterion("ACCOUNTING_SUB <>", value, "accountingSub");
			return (Criteria) this;
		}

		public Criteria andAccountingSubGreaterThan(String value) {
			addCriterion("ACCOUNTING_SUB >", value, "accountingSub");
			return (Criteria) this;
		}

		public Criteria andAccountingSubGreaterThanOrEqualTo(String value) {
			addCriterion("ACCOUNTING_SUB >=", value, "accountingSub");
			return (Criteria) this;
		}

		public Criteria andAccountingSubLessThan(String value) {
			addCriterion("ACCOUNTING_SUB <", value, "accountingSub");
			return (Criteria) this;
		}

		public Criteria andAccountingSubLessThanOrEqualTo(String value) {
			addCriterion("ACCOUNTING_SUB <=", value, "accountingSub");
			return (Criteria) this;
		}

		public Criteria andAccountingSubLike(String value) {
			addCriterion("ACCOUNTING_SUB like", value, "accountingSub");
			return (Criteria) this;
		}

		public Criteria andAccountingSubNotLike(String value) {
			addCriterion("ACCOUNTING_SUB not like", value, "accountingSub");
			return (Criteria) this;
		}

		public Criteria andAccountingSubIn(List<String> values) {
			addCriterion("ACCOUNTING_SUB in", values, "accountingSub");
			return (Criteria) this;
		}

		public Criteria andAccountingSubNotIn(List<String> values) {
			addCriterion("ACCOUNTING_SUB not in", values, "accountingSub");
			return (Criteria) this;
		}

		public Criteria andAccountingSubBetween(String value1, String value2) {
			addCriterion("ACCOUNTING_SUB between", value1, value2,
					"accountingSub");
			return (Criteria) this;
		}

		public Criteria andAccountingSubNotBetween(String value1, String value2) {
			addCriterion("ACCOUNTING_SUB not between", value1, value2,
					"accountingSub");
			return (Criteria) this;
		}

		public Criteria andAccountingAux1IsNull() {
			addCriterion("ACCOUNTING_AUX1 is null");
			return (Criteria) this;
		}

		public Criteria andAccountingAux1IsNotNull() {
			addCriterion("ACCOUNTING_AUX1 is not null");
			return (Criteria) this;
		}

		public Criteria andAccountingAux1EqualTo(String value) {
			addCriterion("ACCOUNTING_AUX1 =", value, "accountingAux1");
			return (Criteria) this;
		}

		public Criteria andAccountingAux1NotEqualTo(String value) {
			addCriterion("ACCOUNTING_AUX1 <>", value, "accountingAux1");
			return (Criteria) this;
		}

		public Criteria andAccountingAux1GreaterThan(String value) {
			addCriterion("ACCOUNTING_AUX1 >", value, "accountingAux1");
			return (Criteria) this;
		}

		public Criteria andAccountingAux1GreaterThanOrEqualTo(String value) {
			addCriterion("ACCOUNTING_AUX1 >=", value, "accountingAux1");
			return (Criteria) this;
		}

		public Criteria andAccountingAux1LessThan(String value) {
			addCriterion("ACCOUNTING_AUX1 <", value, "accountingAux1");
			return (Criteria) this;
		}

		public Criteria andAccountingAux1LessThanOrEqualTo(String value) {
			addCriterion("ACCOUNTING_AUX1 <=", value, "accountingAux1");
			return (Criteria) this;
		}

		public Criteria andAccountingAux1Like(String value) {
			addCriterion("ACCOUNTING_AUX1 like", value, "accountingAux1");
			return (Criteria) this;
		}

		public Criteria andAccountingAux1NotLike(String value) {
			addCriterion("ACCOUNTING_AUX1 not like", value, "accountingAux1");
			return (Criteria) this;
		}

		public Criteria andAccountingAux1In(List<String> values) {
			addCriterion("ACCOUNTING_AUX1 in", values, "accountingAux1");
			return (Criteria) this;
		}

		public Criteria andAccountingAux1NotIn(List<String> values) {
			addCriterion("ACCOUNTING_AUX1 not in", values, "accountingAux1");
			return (Criteria) this;
		}

		public Criteria andAccountingAux1Between(String value1, String value2) {
			addCriterion("ACCOUNTING_AUX1 between", value1, value2,
					"accountingAux1");
			return (Criteria) this;
		}

		public Criteria andAccountingAux1NotBetween(String value1, String value2) {
			addCriterion("ACCOUNTING_AUX1 not between", value1, value2,
					"accountingAux1");
			return (Criteria) this;
		}

		public Criteria andAccountingAux2IsNull() {
			addCriterion("ACCOUNTING_AUX2 is null");
			return (Criteria) this;
		}

		public Criteria andAccountingAux2IsNotNull() {
			addCriterion("ACCOUNTING_AUX2 is not null");
			return (Criteria) this;
		}

		public Criteria andAccountingAux2EqualTo(String value) {
			addCriterion("ACCOUNTING_AUX2 =", value, "accountingAux2");
			return (Criteria) this;
		}

		public Criteria andAccountingAux2NotEqualTo(String value) {
			addCriterion("ACCOUNTING_AUX2 <>", value, "accountingAux2");
			return (Criteria) this;
		}

		public Criteria andAccountingAux2GreaterThan(String value) {
			addCriterion("ACCOUNTING_AUX2 >", value, "accountingAux2");
			return (Criteria) this;
		}

		public Criteria andAccountingAux2GreaterThanOrEqualTo(String value) {
			addCriterion("ACCOUNTING_AUX2 >=", value, "accountingAux2");
			return (Criteria) this;
		}

		public Criteria andAccountingAux2LessThan(String value) {
			addCriterion("ACCOUNTING_AUX2 <", value, "accountingAux2");
			return (Criteria) this;
		}

		public Criteria andAccountingAux2LessThanOrEqualTo(String value) {
			addCriterion("ACCOUNTING_AUX2 <=", value, "accountingAux2");
			return (Criteria) this;
		}

		public Criteria andAccountingAux2Like(String value) {
			addCriterion("ACCOUNTING_AUX2 like", value, "accountingAux2");
			return (Criteria) this;
		}

		public Criteria andAccountingAux2NotLike(String value) {
			addCriterion("ACCOUNTING_AUX2 not like", value, "accountingAux2");
			return (Criteria) this;
		}

		public Criteria andAccountingAux2In(List<String> values) {
			addCriterion("ACCOUNTING_AUX2 in", values, "accountingAux2");
			return (Criteria) this;
		}

		public Criteria andAccountingAux2NotIn(List<String> values) {
			addCriterion("ACCOUNTING_AUX2 not in", values, "accountingAux2");
			return (Criteria) this;
		}

		public Criteria andAccountingAux2Between(String value1, String value2) {
			addCriterion("ACCOUNTING_AUX2 between", value1, value2,
					"accountingAux2");
			return (Criteria) this;
		}

		public Criteria andAccountingAux2NotBetween(String value1, String value2) {
			addCriterion("ACCOUNTING_AUX2 not between", value1, value2,
					"accountingAux2");
			return (Criteria) this;
		}

		public Criteria andAccountingAux3IsNull() {
			addCriterion("ACCOUNTING_AUX3 is null");
			return (Criteria) this;
		}

		public Criteria andAccountingAux3IsNotNull() {
			addCriterion("ACCOUNTING_AUX3 is not null");
			return (Criteria) this;
		}

		public Criteria andAccountingAux3EqualTo(String value) {
			addCriterion("ACCOUNTING_AUX3 =", value, "accountingAux3");
			return (Criteria) this;
		}

		public Criteria andAccountingAux3NotEqualTo(String value) {
			addCriterion("ACCOUNTING_AUX3 <>", value, "accountingAux3");
			return (Criteria) this;
		}

		public Criteria andAccountingAux3GreaterThan(String value) {
			addCriterion("ACCOUNTING_AUX3 >", value, "accountingAux3");
			return (Criteria) this;
		}

		public Criteria andAccountingAux3GreaterThanOrEqualTo(String value) {
			addCriterion("ACCOUNTING_AUX3 >=", value, "accountingAux3");
			return (Criteria) this;
		}

		public Criteria andAccountingAux3LessThan(String value) {
			addCriterion("ACCOUNTING_AUX3 <", value, "accountingAux3");
			return (Criteria) this;
		}

		public Criteria andAccountingAux3LessThanOrEqualTo(String value) {
			addCriterion("ACCOUNTING_AUX3 <=", value, "accountingAux3");
			return (Criteria) this;
		}

		public Criteria andAccountingAux3Like(String value) {
			addCriterion("ACCOUNTING_AUX3 like", value, "accountingAux3");
			return (Criteria) this;
		}

		public Criteria andAccountingAux3NotLike(String value) {
			addCriterion("ACCOUNTING_AUX3 not like", value, "accountingAux3");
			return (Criteria) this;
		}

		public Criteria andAccountingAux3In(List<String> values) {
			addCriterion("ACCOUNTING_AUX3 in", values, "accountingAux3");
			return (Criteria) this;
		}

		public Criteria andAccountingAux3NotIn(List<String> values) {
			addCriterion("ACCOUNTING_AUX3 not in", values, "accountingAux3");
			return (Criteria) this;
		}

		public Criteria andAccountingAux3Between(String value1, String value2) {
			addCriterion("ACCOUNTING_AUX3 between", value1, value2,
					"accountingAux3");
			return (Criteria) this;
		}

		public Criteria andAccountingAux3NotBetween(String value1, String value2) {
			addCriterion("ACCOUNTING_AUX3 not between", value1, value2,
					"accountingAux3");
			return (Criteria) this;
		}

		public Criteria andAccountingAbsIsNull() {
			addCriterion("ACCOUNTING_ABS is null");
			return (Criteria) this;
		}

		public Criteria andAccountingAbsIsNotNull() {
			addCriterion("ACCOUNTING_ABS is not null");
			return (Criteria) this;
		}

		public Criteria andAccountingAbsEqualTo(String value) {
			addCriterion("ACCOUNTING_ABS =", value, "accountingAbs");
			return (Criteria) this;
		}

		public Criteria andAccountingAbsNotEqualTo(String value) {
			addCriterion("ACCOUNTING_ABS <>", value, "accountingAbs");
			return (Criteria) this;
		}

		public Criteria andAccountingAbsGreaterThan(String value) {
			addCriterion("ACCOUNTING_ABS >", value, "accountingAbs");
			return (Criteria) this;
		}

		public Criteria andAccountingAbsGreaterThanOrEqualTo(String value) {
			addCriterion("ACCOUNTING_ABS >=", value, "accountingAbs");
			return (Criteria) this;
		}

		public Criteria andAccountingAbsLessThan(String value) {
			addCriterion("ACCOUNTING_ABS <", value, "accountingAbs");
			return (Criteria) this;
		}

		public Criteria andAccountingAbsLessThanOrEqualTo(String value) {
			addCriterion("ACCOUNTING_ABS <=", value, "accountingAbs");
			return (Criteria) this;
		}

		public Criteria andAccountingAbsLike(String value) {
			addCriterion("ACCOUNTING_ABS like", value, "accountingAbs");
			return (Criteria) this;
		}

		public Criteria andAccountingAbsNotLike(String value) {
			addCriterion("ACCOUNTING_ABS not like", value, "accountingAbs");
			return (Criteria) this;
		}

		public Criteria andAccountingAbsIn(List<String> values) {
			addCriterion("ACCOUNTING_ABS in", values, "accountingAbs");
			return (Criteria) this;
		}

		public Criteria andAccountingAbsNotIn(List<String> values) {
			addCriterion("ACCOUNTING_ABS not in", values, "accountingAbs");
			return (Criteria) this;
		}

		public Criteria andAccountingAbsBetween(String value1, String value2) {
			addCriterion("ACCOUNTING_ABS between", value1, value2,
					"accountingAbs");
			return (Criteria) this;
		}

		public Criteria andAccountingAbsNotBetween(String value1, String value2) {
			addCriterion("ACCOUNTING_ABS not between", value1, value2,
					"accountingAbs");
			return (Criteria) this;
		}

		public Criteria andModelNoIsNull() {
			addCriterion("MODEL_NO is null");
			return (Criteria) this;
		}

		public Criteria andModelNoIsNotNull() {
			addCriterion("MODEL_NO is not null");
			return (Criteria) this;
		}

		public Criteria andModelNoEqualTo(String value) {
			addCriterion("MODEL_NO =", value, "modelNo");
			return (Criteria) this;
		}

		public Criteria andModelNoNotEqualTo(String value) {
			addCriterion("MODEL_NO <>", value, "modelNo");
			return (Criteria) this;
		}

		public Criteria andModelNoGreaterThan(String value) {
			addCriterion("MODEL_NO >", value, "modelNo");
			return (Criteria) this;
		}

		public Criteria andModelNoGreaterThanOrEqualTo(String value) {
			addCriterion("MODEL_NO >=", value, "modelNo");
			return (Criteria) this;
		}

		public Criteria andModelNoLessThan(String value) {
			addCriterion("MODEL_NO <", value, "modelNo");
			return (Criteria) this;
		}

		public Criteria andModelNoLessThanOrEqualTo(String value) {
			addCriterion("MODEL_NO <=", value, "modelNo");
			return (Criteria) this;
		}

		public Criteria andModelNoLike(String value) {
			addCriterion("MODEL_NO like", value, "modelNo");
			return (Criteria) this;
		}

		public Criteria andModelNoNotLike(String value) {
			addCriterion("MODEL_NO not like", value, "modelNo");
			return (Criteria) this;
		}

		public Criteria andModelNoIn(List<String> values) {
			addCriterion("MODEL_NO in", values, "modelNo");
			return (Criteria) this;
		}

		public Criteria andModelNoNotIn(List<String> values) {
			addCriterion("MODEL_NO not in", values, "modelNo");
			return (Criteria) this;
		}

		public Criteria andModelNoBetween(String value1, String value2) {
			addCriterion("MODEL_NO between", value1, value2, "modelNo");
			return (Criteria) this;
		}

		public Criteria andModelNoNotBetween(String value1, String value2) {
			addCriterion("MODEL_NO not between", value1, value2, "modelNo");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_TIME =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_TIME <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("CREATE_TIME >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_TIME >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterionForJDBCDate("CREATE_TIME <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_TIME <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterionForJDBCDate("CREATE_TIME in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("CREATE_TIME not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CREATE_TIME between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CREATE_TIME not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("UPDATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("UPDATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterionForJDBCDate("UPDATE_TIME =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("UPDATE_TIME <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("UPDATE_TIME >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("UPDATE_TIME >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterionForJDBCDate("UPDATE_TIME <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("UPDATE_TIME <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterionForJDBCDate("UPDATE_TIME in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("UPDATE_TIME not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("UPDATE_TIME between", value1, value2,
					"updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("UPDATE_TIME not between", value1, value2,
					"updateTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SITBAS_XFD_TMK.CW_VOUCHER_MODEL_INFO
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}