package com.billionsfinance.bas.entity.voucher.model;

import java.math.BigDecimal;
import java.util.Date;

public class CwVoucherModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL.ID
	 * @mbggenerated
	 */
	private BigDecimal id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL.MODEL_NO
	 * @mbggenerated
	 */
	private String modelNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL.MODEL_NAME
	 * @mbggenerated
	 */
	private String modelName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL.CREATE_TIME
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL.UPDATE_TIME
	 * @mbggenerated
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL.ID
	 * @return  the value of SITBAS_XFD_TMK.CW_VOUCHER_MODEL.ID
	 * @mbggenerated
	 */
	public BigDecimal getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL.ID
	 * @param id  the value for SITBAS_XFD_TMK.CW_VOUCHER_MODEL.ID
	 * @mbggenerated
	 */
	public void setId(BigDecimal id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL.MODEL_NO
	 * @return  the value of SITBAS_XFD_TMK.CW_VOUCHER_MODEL.MODEL_NO
	 * @mbggenerated
	 */
	public String getModelNo() {
		return modelNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL.MODEL_NO
	 * @param modelNo  the value for SITBAS_XFD_TMK.CW_VOUCHER_MODEL.MODEL_NO
	 * @mbggenerated
	 */
	public void setModelNo(String modelNo) {
		this.modelNo = modelNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL.MODEL_NAME
	 * @return  the value of SITBAS_XFD_TMK.CW_VOUCHER_MODEL.MODEL_NAME
	 * @mbggenerated
	 */
	public String getModelName() {
		return modelName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL.MODEL_NAME
	 * @param modelName  the value for SITBAS_XFD_TMK.CW_VOUCHER_MODEL.MODEL_NAME
	 * @mbggenerated
	 */
	public void setModelName(String modelName) {
		this.modelName = modelName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL.CREATE_TIME
	 * @return  the value of SITBAS_XFD_TMK.CW_VOUCHER_MODEL.CREATE_TIME
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL.CREATE_TIME
	 * @param createTime  the value for SITBAS_XFD_TMK.CW_VOUCHER_MODEL.CREATE_TIME
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL.UPDATE_TIME
	 * @return  the value of SITBAS_XFD_TMK.CW_VOUCHER_MODEL.UPDATE_TIME
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SITBAS_XFD_TMK.CW_VOUCHER_MODEL.UPDATE_TIME
	 * @param updateTime  the value for SITBAS_XFD_TMK.CW_VOUCHER_MODEL.UPDATE_TIME
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}